### ISSUE TITLE
Bug in wizard state persistence in update scenario

### ISSUE THREAD

**Issue by gathogojr** [OData/ODataConnectedService#106]
When **updating** Connected Service, if you navigate to Schema Types or Function/Action Imports page and make a change, then navigate away from that wizard page, then navigate back the wizard page where you made the change, it's overwritten by the initial settings that were already saved in the settings file.

#### Version of the Project affected
ODataConnectedService v0.9.0
Visual Studio 2017 & 2019
Microsoft.Odata.Client v7.6.4

#### To Reproduce
1. Create an OData client against Trippin service
2. On the wizard page for Function/Action Imports exclude ResetDataSource
3. Finalize the generation of Connected Service proxy
4. Next, update the Connected Service
5. On the wizard page for Function/Action Imports exclude (uncheck) GetNearestAirport
6. Click Next to go to the Settings wizard page
7. Click Prev to navigate back to the Function/Action Imports wizard page
8. The Function/Action you unchecked in Step 5 is checked

Note: Similar behavior can be reproduced on Schema Types wizard page

#### Expected behavior
Changes made when updating Connected Service not to be overwritten by saved settings when navigating back to the page where the change was made.

#### Actual behavior
Changes made overwritten by saved settings

#### Screenshots
N/A

#### Additional context
N/A

**Comment by gathogojr** [comment]
@unchase Thanks for being an active contributor to OCS. I think this issue would be of interest to you

**Comment by unchase** [comment]
@gathogojr This behavior was conceived. I wrote about this in the comments on PR https://github.com/OData/ODataConnectedService/pull/78#issuecomment-607859203

> ... data is restored when leaving then entering wizard pages

But this is only if we enter to the page again after leaving.

Do you think it's worth changing the behavior?

**Comment by gathogojr** [comment]
@unchase If the behaviour was contemplated don't jump into it for now. I'll have a discussion with the rest of the team and revert. Thanks

**Comment by unchase** [comment]
@gathogojr Anyway, added a fix to PR #107
Apply it if necessary.
