### ISSUE TITLE
Harmonize ordering and naming of Schema Types and Function/Action Imports wizard pages

### ISSUE THREAD

**Issue by gathogojr** [OData/ODataConnectedService#108]
### Issue description
1. Currently, if say I have a function import _GetNearestAirport_ as the only object that depends on _Airport_ entity type, and I don't need either to be emitted on the Connected Service proxy, I'm forced to first skip **Schema Types** wizard page, go to the **Function/Action Imports** wizard page and uncheck it, before going back to the **Schema Types** wizard page to uncheck _Airport_
2. The title on the **Schema Types** wizard page is **Schema Selection** while the title on the **Function/Action Imports** wizard page is **Object Selection**

#### Proposed solution
1. Since **Function/Action Imports** depends on **Schema Types** and not the other way around, I believe the logical thing would be to have **Function/Action Imports** wizard page appear above **Schema Types** wizard page. That way, if I uncheck a function or action import on the **Function/Action Imports** wizard page, then as I proceed to the **Schema Types** wizard page I'll not having any trouble unchecking the schema types it depends on in a scenario similar to the one described above
2. Harmonize the naming:-
   - Title for **Schema Types** wizard page could be **Schema Types Selection**
   - Title for **Function/Action Imports** wizard page could be **Function/Action Imports Selection**
   - Or any suitable naming so long as its harmonious

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by gathogojr** [comment]
cc @paulodero

**Comment by paulodero** [comment]
@gathogojr Scenario 1 is not correct. At least how I designed it, you don't need to go to operation imports page to unselect  `GetNearestAirport ` function before unselecting `Airport`. When on the schema type selection page when you unselect `Airport`, all operation imports which depends on `Airport `will be automatically unselected to ensure code generated compiles. If that is not the case then it is a bug and should be fixed.

**Comment by gathogojr** [comment]
@paulodero Would the behaviour you described apply to schema types as well? Such that if say I unselected Airport it'd cause Flight schema type to be unselected as well if it depends on it?

**Comment by habbes** [comment]
> @paulodero Would the behaviour you described apply to schema types as well? Such that if say I unselected Airport it'd cause Flight schema type to be unselected as well if it depends on it?

@gathogojr  No, in that case, when you leave the page it detects that a required dependency is unselect and then auto-selects Airport

@paulodero  could confirm this.

**Comment by gathogojr** [comment]
Okay. I might have misunderstood how it was designed to work

**Comment by paulodero** [comment]
> @paulodero Would the behaviour you described apply to schema types as well? Such that if say I unselected Airport it'd cause Flight schema type to be unselected as well if it depends on it?
> 
> @gathogojr  No, in that case, when you leave the page it detects that a required dependency is unselected and then auto-selects Airport
> @paulodero  could confirm this.

Yes, this is exactly what happens.
