### ISSUE TITLE
An exception occurs in CreateXmlReader() when there are more than one Csdl files in the assembly

### ISSUE THREAD

**Issue by thetriplet3** [OData/ODataConnectedService#111]
### Describe the bug
When the container tries to read the path of Csdl.xml in CreateXmlReader(), an error occurs when there are more than one Csdl.xml files in the assembly.

private const string filePath = @"Csdl.xml";

```
private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    **var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));**


//Rest of the code
            }
```

The issue is it tries to find only one ending with Csdl.xml when there are more than one Csdl.xml files. In my case I have generated stubs for 3 different endpoints in 3 different folders. All of them had Csdl.xml

Suggested Fix - Rename the Csdl.xml to **[ServiceName]Csdl.xml**
 
#### Version of the Project affected
ODataConnectedService v0.9.0
VisualStudio Version v16.5
Microsoft.Odata.Client v7.6.4

#### To Reproduce
1. Generate Stubs for two (or more)different end points.
2. Create an instance of any container

#### Expected behavior
Container instantiated without any error 

#### Actual behavior
An error occurs - System.InvalidOperationException: Sequence contains more than one matching element

#### Additional context
Error Stack
Exception: The type initializer for 'GeneratedEdmModel' threw an exception. ---> System.TypeInitializationException: The type initializer for 'GeneratedEdmModel' threw an exception. ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at ProjectService.DefaultContainer.GeneratedEdmModel.CreateXmlReader() in ... <rest of the stack>

**Comment by bwn-z** [comment]
хотел сообщить вам, что эта проблема все еще сохраняется, потому что serviceName является константой. Может есть смысл дать пользователю право переназначать через опции? --имя-службы | -сн.

https://github.com/OData/ODataConnectedService/blob/11df9341833a1ba5b7dda8ae105ee49c5558cadf/src/Microsoft.OData.Cli/GenerateCommand.cs#L214
