### ISSUE TITLE
Fix documentation for generating and using OData client

### ISSUE THREAD

**Issue by unchase** [OData/ODataConnectedService#119]
Need to fix (documentation is out of date):

* [Create an OData v4 Client App (C#)](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-client-app)
* [Calling an OData Service From a .NET Client (C#)](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v3/calling-an-odata-service-from-a-net-client)
* [Client code gen tool](https://docs.microsoft.com/odata/client/code-generation-tool)

**Comment by unchase** [comment]
Also in [OData Connected Service v0.8.0 Release](https://devblogs.microsoft.com/odata/odata-connected-service-v0-8-0-release/):

![doc](https://user-images.githubusercontent.com/29679226/82183252-4c6be800-98ee-11ea-98f7-65128b11d543.png)

**Comment by habbes** [comment]
Changes have been made to the docs since. The main documentation for OData Connected Service has been moved to https://docs.microsoft.com/en-us/odata/connectedservice/getting-started
