### ISSUE TITLE
Types auto-selected when moving to the operations page even without being required

### ISSUE THREAD

**Issue by habbes** [OData/ODataConnectedService#120]
### Describe the bug
When  you move to the Operations Import page while updating an OData connected service, unselected schema types that are used by the operations in the list get selected, even though none of the operations that require them are selected.

#### Version of the Project affected
Microsoft.OData.ConnectedService v0.10.x

#### To Reproduce
1. Create an OData Connected Service based on the [Trippin sample service](https://services.odata.org/TripPinRESTierService/$metadata)
2. When creating the connected service, make sure all the operation imports are unselected and the schema types `PersonGender`, `Person`, `Employee` are unselected (you can also unselect all schema types if you prefer)
3. After the connected service has been saved, update it
4. When updating the connected service, don't select any new schema types and move to the operations page, the operations should still also be unselected
5. Then move back from the operations page to the schema types page and check whether previously unselected types like `PersonGender` and `Person` are unselected

#### Expected behavior
- The types that were unselected, like `PersonGender` and `Person` are unselected
#### Actual behavior
A clear and concise description of what happens.
- Types like `PersonGender` and `Person` are auto-selected even though there's no selected schema type or operation that depends on them.

**Comment by unchase** [comment]
@habbes Can not reproduce the issue.

**Comment by habbes** [comment]
@unchase Thanks for pointing this out. This was fixed by PR #103 but issue was not closed.
