### ISSUE TITLE
Deselecting a schema type does not exclude its bound operations

### ISSUE THREAD

**Issue by unchase** [OData/ODataConnectedService#130]
### Describe the bug
Deselecting a schema type does not exclude its bound operations. This operations will be added to generated code. Will get compilation errors.

#### Version of the Project affected
Microsoft.OData.ConnectedService v0.10.x

#### To Reproduce

1. Create an OData Connected Service based on the [Microsoft Graph service](https://graph.microsoft.com/v1.0/$metadata);
2. Move to the schema types page, all types should be selected by default;
3. Deselect, for example, `user` schema type (which has bound operations);
4. Proceed to the function/action imports page, there is no operation imports;
5. Click **Finish** to generate code;
6. Try to build project.

#### Expected behavior
Deselecting schema types should deselect its bound operations.

#### Actual behavior
Deselecting schema types does not affect its bound operations.

#### Screenshots
* Use [Microsoft Graph service](https://graph.microsoft.com/v1.0/$metadata) metadata:

![page1](https://user-images.githubusercontent.com/29679226/82199960-0ff8b600-9907-11ea-90d1-d205804e268d.png)

* Deselecting `user` schema type:

![page2](https://user-images.githubusercontent.com/29679226/82200111-46cecc00-9907-11ea-9486-143524b5216e.png)

* `user` schema type and one of its bound operation:

![edm](https://user-images.githubusercontent.com/29679226/82200786-218e8d80-9908-11ea-868e-e25fa5692915.png)

* There is no operation imports:

![page3](https://user-images.githubusercontent.com/29679226/82200083-3c143700-9907-11ea-9b49-a69785dd9c77.png)

* Compilations errors:

![error](https://user-images.githubusercontent.com/29679226/82201001-61ee0b80-9908-11ea-8e80-ef47f39d2047.png)

**Comment by paulodero** [comment]
@unchase In your repro steps, which types did you unselect because with the current version it should not be possible to only unselect the `user `type. It will be automatically included when you exit the page because it is required by other selected related types.

**Comment by unchase** [comment]
> @unchase In your repro steps, which types did you unselect because with the current version it should not be possible to only unselect the `user `type. It will be automatically included when you exit the page because it is required by other selected related types.

@paulodero The deselection of types automatically deselect all related types in such a way that when leaving the page, an error with simultaneous including required types cannot occur.

Deselection and selection of types are consistent with related types in both directions. In addition, it consistent with deselection and selection of bound operations.

A situation cannot arise when types or bound operations are selected without its required types.

**Comment by paulodero** [comment]
> > @unchase In your repro steps, which types did you unselect because with the current version it should not be possible to only unselect the `user `type. It will be automatically included when you exit the page because it is required by other selected related types.
> 
> @paulodero The deselection of types automatically deselect all related types in such a way that when leaving the page, an error with simultaneous including required types cannot occur.
> 
> Deselection and selection of types are consistent with related types in both directions. In addition, it consistent with deselection and selection of bound operations.
> 
> A situation cannot arise when types or bound operations are selected without its required types.

That is perfect @unchase. What I mean is a change on the  UI. If we can include the bound operations as children of related types(tree-like) in the same type window would be nice. Makes the work of the user selecting and deselecting easier and also a better visual impression. What do you think about this?

**Comment by unchase** [comment]
> > > @unchase In your repro steps, which types did you unselect because with the current version it should not be possible to only unselect the `user `type. It will be automatically included when you exit the page because it is required by other selected related types.
> > 
> > 
> > @paulodero The deselection of types automatically deselect all related types in such a way that when leaving the page, an error with simultaneous including required types cannot occur.
> > Deselection and selection of types are consistent with related types in both directions. In addition, it consistent with deselection and selection of bound operations.
> > A situation cannot arise when types or bound operations are selected without its required types.
> 
> That is perfect @unchase. What I mean is a change on the UI. If we can include the bound operations as children of related types(tree-like) in the same type window would be nice. Makes the work of the user selecting and deselecting easier and also a better visual impression. What do you think about this?

@paulodero I think it is a good idea. I need to explore this possibility, it will take some time.

**Comment by unchase** [comment]
> > > > @unchase In your repro steps, which types did you unselect because with the current version it should not be possible to only unselect the `user `type. It will be automatically included when you exit the page because it is required by other selected related types.
> > > 
> > > 
> > > @paulodero The deselection of types automatically deselect all related types in such a way that when leaving the page, an error with simultaneous including required types cannot occur.
> > > Deselection and selection of types are consistent with related types in both directions. In addition, it consistent with deselection and selection of bound operations.
> > > A situation cannot arise when types or bound operations are selected without its required types.
> > 
> > 
> > That is perfect @unchase. What I mean is a change on the UI. If we can include the bound operations as children of related types(tree-like) in the same type window would be nice. Makes the work of the user selecting and deselecting easier and also a better visual impression. What do you think about this?
> 
> @paulodero I think it is a good idea. I need to explore this possibility, it will take some time.

@paulodero done!
