### ISSUE TITLE
Collection of enum properties is not added to related types Dictionary for structured types

### ISSUE THREAD

**Issue by unchase** [OData/ODataConnectedService#135]
### Describe the bug
Selecting a schema type does not include its related schema types (enums) from collection of enum properties. This properties will not be added to generated code. Will get compilation errors.

#### Version of the Project affected
ODataConnectedService v0.10.x

#### To Reproduce

1. Create an OData Connected Service based on the [Microsoft Graph service](https://graph.microsoft.com/v1.0/$metadata);
2. Move to the schema types page, all types should be selected by default;
3. Deselect all schema types;
4. Select, for example, `managedAppRegistration` schema type (which has `Collection(graph.managedFlaggedReason)` property);
4. See that `managedAppFlaggedReason` does not selected;
5. Click **Finish** to generate code;
6. Try to build project.

#### Expected behavior
Selecting schema types should select all its required types.

#### Actual behavior
Selecting schema types does not select all its required types.

#### Screenshots
* Schema types Selection:

![bug](https://user-images.githubusercontent.com/29679226/83243667-e9f4d080-a1a6-11ea-8875-7750dc7060b5.png)

* Example1 - `managedAppRegistration` type with `Collection(graph.managedFlaggedReason)` property:

![bug3](https://user-images.githubusercontent.com/29679226/83243698-f842ec80-a1a6-11ea-84db-25bfa51b6130.png)

* Example2 - `managedAppProtection` type with `Collection(graph.managedAppDataStorageLocation)` property:

![bug4](https://user-images.githubusercontent.com/29679226/83243718-fbd67380-a1a6-11ea-8692-4752ea1915d7.png)

* Compilations errors:

![bug2](https://user-images.githubusercontent.com/29679226/83243680-f0834800-a1a6-11ea-84bb-70826e436279.png)

**Comment by ElizabethOkerio** [comment]
@unchase the issue is still there.. seems it has no been fixed. When I select <code> managedAppRegistration </code. schema type, this <code> managedAppFlaggedReason <code> does not get select hence getting the error you described above.
