### ISSUE TITLE
Allow downloading  csdl document from the web

### ISSUE THREAD

**Issue by g2mula** [OData/ODataConnectedService#149]
### Is your feature request related to a problem? Please describe.
I tried generating a service from a xml hosted on the web. OCS automatically appends /$metadata to the end of the address resulting in a 404.

#### Describe the solution you'd like
Maybe fallback to the address as exactly specified if a 404 is gotten when appending /$metadata

#### Describe alternatives you've considered
I downloaded the xml file and was able to continue.

**Comment by unchase** [comment]
Hi, @g2mula 

OCS generates code based on the metadata, so `/$metadata` should always be added at the end if this is missed.

**Comment by g2mula** [comment]
Looked into the specification and it would seem to be true that the $metadata is a required part to get a service metadata...
Closing this but could be helpful to point this out in some documentation
cc @habbes 
Will close this
