### ISSUE TITLE
Selected Schema Type Ignored When Combined with Add code templates option

### ISSUE THREAD

**Issue by g2mula** [OData/ODataConnectedService#150]
### Describe the bug
For a certain combination of selections, selected schema types is ignored.

#### Version of the Project affected
ODataConnectedService v0.10.0
VisualStudio Version v16.5.4
Microsoft.Odata.Client v7.6.4

#### To Reproduce
In the wizard
1. Schema Type Selection -> Select a single file
2. Settings > Advanced
3. Select "Add code templates (Whether to include the ......)"
4. Finish

#### Expected behavior
One type should be generated.

#### Actual behavior
The generator attempts to generate all files;

It would seem the ```public const string ExcludedSchemaTypes = "";``` does not get updated?

### Something else
Could you also add a button/link in the wizard for easily getting the OCS version? OData version etc? For easily getting the information being asked for up there ;-)

**Comment by unchase** [comment]
Hi, @g2mula 

The issue does not reproduced for me.
Can you attach screenshots or more better - animation?

**Comment by g2mula** [comment]
Any good resources on how to make animations?
In the meantime, some screenshots
Address is from the TripPinService

![image](https://user-images.githubusercontent.com/5147931/85045151-4429f580-b197-11ea-85ce-f7c5d80db01b.png)

![image](https://user-images.githubusercontent.com/5147931/85045200-52781180-b197-11ea-9541-5019a51ce351.png)

![image](https://user-images.githubusercontent.com/5147931/85045226-5c9a1000-b197-11ea-9243-a9db188fbac3.png)

Advanced Settings:

![image](https://user-images.githubusercontent.com/5147931/85045299-75a2c100-b197-11ea-82bc-fec5061ca838.png)

Expanding Reference.tt
![image](https://user-images.githubusercontent.com/5147931/85045440-a125ab80-b197-11ea-9712-44e0c949e9a9.png)

Second time, no selecting "Add code templates......"
![image](https://user-images.githubusercontent.com/5147931/85045600-d631fe00-b197-11ea-8e6d-d348a266657e.png)

Expanding
![image](https://user-images.githubusercontent.com/5147931/85045676-f82b8080-b197-11ea-8e3d-b1667ec090fa.png)

**Comment by unchase** [comment]
Why did the issue become open?
