### ISSUE TITLE
Assembly 'Microsoft.OData.Edm' with identity 'Microsoft.OData.Edm, Version=7.7.0.0, which has a higher version than referenced assembly 'System.Text.Json' with identity 'System.Text.Json, Version=4.0.1.0

### ISSUE THREAD

**Issue by UM001** [OData/ODataConnectedService#159]
I encountered similar issue as reported here:
https://community.dynamics.com/365/f/dynamics-365-general-forum/395636/adding-d365-odata-client-via-odata-connected-service-wont-work-vs2019

Error CS1705 Assembly 'Microsoft.OData.Edm' with identity 'Microsoft.OData.Edm, Version=7.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'System.Text.Json, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Text.Json' with identity 'System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' D365ToAzure C:\Users\grapf\source\repos\D365ToAzure\D365ToAzure\Connected Services\D365ODataClient\D365ODataClient.cs 55380 Active

I just wanted to let you know. it can be resolved by installing nuget System.Text.Json .

**Comment by habbes** [comment]
@UM001 Thank you for reporting it. I can confirm that installing `System.Text.Json` from Nuget currently resolves the issue.

**Comment by habbes** [comment]
We should investigate this to determine whether this is an issue with OCS, Edm or something else.

**Comment by marabooy** [comment]
@unchase and @habbes https://github.com/OData/odata.net/issues/1878 may solve this.
