### ISSUE TITLE
Secure binary serialization is not supported on this platform.

### ISSUE THREAD

**Issue by UM001** [OData/ODataConnectedService#162]
I am trying to inject bearer token in .netcore for oData of Dynamics D365Fo. I cannot get a proper example. One is about using delegatehandler which I have working for plain posts to an api service. Other is with OnMessageCreating . However, on last step before last line firstdefault() is throws Secure binary serialization is not supported on this platform.

What do I do wrong? I want basically a http factory to avoid socket exhaustion.

`  var config = TestSetup.GetIConfigurationRoot(Directory.GetCurrentDirectory()); 

            var configD365Fo = new AuthenticationConfig();
            config.GetSection("D365Fo").Bind(configD365Fo);

            var protectedApiBearerTokenHandler = new ProtectedApiBearerTokenHandler()
            {
                AuthenticationConfig = configD365Fo
            };

            var sc = new ServiceCollection();

            sc.AddTransient<ProtectedApiBearerTokenHandler>();

            sc
            .AddODataClient("Resources")
            .ConfigureODataClient(dsc =>
            {
                dsc.BaseUri = new Uri(configD365Fo.BaseAddress);
                dsc.Configurations.RequestPipeline.OnMessageCreating = (args) =>
                {
                    var request = new HttpWebRequestMessage(args);

                    //Setting the values in the Authorization header
                    request.SetHeader("Authorization", "Bearer <your_token>");

                    return request;
                };
            })
            .AddHttpClient()
            .AddHttpMessageHandler(provider =>
            {
                var handler = provider.GetRequiredService<ProtectedApiBearerTokenHandler>();
                handler.AuthenticationConfig = configD365Fo;
                handler.Name = "D365Fo";

                return handler;
            });
            var sp = sc.BuildServiceProvider();

            var service = sp.GetService<IODataClientFactory>();
            var client = service.CreateClient<Resources>(new Uri(configD365Fo.BaseAddress));

            var result = client.Customers.FirstOrDefault();`

**Comment by UM001** [comment]
I reverted back to version 7.6.4. I came across this.
https://github.com/OData/odata.net/issues/1833
For some reason I get 401 Unauthorized error now although with own developed httpclient I do not get such errors. I will further investigate. I am trying to use all in .netcore 3.1

**Comment by UM001** [comment]
Will this be fixed in newer version 7.7.x ? Is assistance required that I upgrade once more to latest version to see if issue is still there?

**Comment by ElizabethOkerio** [comment]
@UM001. yes this will be fixed in a newer version release.
