### ISSUE TITLE
How to inject ODataContext in startup and only have 1 httphandler?

### ISSUE THREAD

**Issue by UM001** [OData/ODataConnectedService#164]
I need some help in understanding how to add 1 instance with a httphandler to inject bearer tokens only once and then reuse it in the application with interface reference.

I think I need to implement this and inject it through startup file:
https://docs.microsoft.com/en-us/odata/odatalib/di-support

But also see this, which I do not get to work as DI:
https://docs.microsoft.com/en-us/odata/client/using-extensions

So what to do?
I finally want to create a controller in which I have IODataContext which gives fresh reusable instance of ODataContext which I can use to call web service. The bearer token should be created automatically with own messagehandler, onmessagecreating or sendrequest2.  Those I have working. Sample: of service using own httpclient and httpmessage handler:

`
[TestClass]
public class D365FoServiceTestInit
{
  public IConfiguration Configuration { get; set; }

        protected D365FoService _d365FoService { get; set; }

        [TestInitialize]
        public void Init()
        {
            Configuration = TestSetup.GetIConfigurationRoot(Directory.GetCurrentDirectory());

            var configD365Fo = new AuthenticationConfig();
            Configuration.GetSection("D365Fo").Bind(configD365Fo);

            IServiceCollection services = new ServiceCollection();
            services.AddSingleton<IConfiguration>(Configuration);

            services.AddLogging();
            services.AddScoped<MSALBearerTokenHandler>()
            //services.AddScoped<ADALBearerTokenHandler>()
            //.AddScoped<ID365FoService, D365FoService>()
            .AddHttpClient<D365FoService>(c =>
            //.AddHttpClient<D365FoService>(name: "D365Fo", c =>
            {
                c.BaseAddress = new Uri(configD365Fo.BaseAddress);                
            })
            .AddHttpMessageHandler(provider =>
            {
                var handler = provider.GetRequiredService<MSALBearerTokenHandler>();
                //var handler = provider.GetRequiredService<ADALBearerTokenHandler>();
                handler.AuthenticationConfig = configD365Fo;
               
                return handler;
            });

            var serviceProvider = services.BuildServiceProvider(); 
            
            //HttpClient configuredClient =
            //     serviceProvider
            //         .GetRequiredService<IHttpClientFactory>()
            //         .CreateClient("D365Fo");

            _d365FoService = serviceProvider.GetRequiredService<D365FoService>();
        }
    }`

**Comment by UM001** [comment]
This code is working: however, see comments on createclient(). I still need to have url and do a createclient..
`
            Configuration = TestSetup.GetIConfigurationRoot(Directory.GetCurrentDirectory())
            IServiceCollection services = new ServiceCollection();
            services.AddSingleton<IConfiguration>(Configuration);

            services.AddLogging();
            //services.AddScoped<IResources, Resources>();

            services.AddScoped<MSALBearerTokenHandler>();
            //services.AddScoped<ADALBearerTokenHandler>();            
            services.AddODataClient("Resources")
                //.ConfigureODataClient(c => c.BaseUri = new Uri($"{Configuration.BaseAddress}/data"))
                .AddHttpClient()
                .ConfigureHttpClient(c =>
                {
                    c.BaseAddress = new Uri($"{Configuration.BaseAddress}/data");
                })

                .AddHttpMessageHandler(provider =>
                {
                    var handler = provider.GetRequiredService<MSALBearerTokenHandler>();
                    //var handler = provider.GetRequiredService<ADALBearerTokenHandler>();
                    return handler;
                });

            var serviceProvider = services.BuildServiceProvider();
            var service = serviceProvider.GetService<IODataClientFactory>();

            try
            {
                var client1 = service.CreateClient<Resources>(new Uri($"{Configuration}/data"), "Resources");
                //^Not desired because of url to be added. Strong typed preferred.
                //why is var client1 = service.CreateClient<Resources>() or var client1 = service.CreateClient("Resources")
                //not possible?
                //is it possible to make a IResource interface on Resource and use that instead of create()?
                //like PeopleController(IResource resource)
                //{ 
                //  _resource = resource
                //}
                //_resource.ProductsV2.ByKey(productNumber: productNumber).GetValueAsync();


                string productNumber = "xxxx";
                var result1 = await client1.ProductsV2.ByKey(productNumber: productNumber).GetValueAsync();
                Assert.AreEqual(result1.ProductNumber, productNumber);
                for (int i = 0; i < 20; i++)
                {
                    var result2 = await client1.ProductsV2.ByKey(productNumber: productNumber).GetValueAsync();
                    Assert.AreEqual(result2.ProductNumber, productNumber);
                    //^looks like lot of activity with netstat
                }
                //var client2 = serviceProvider.GetRequiredService<IResources>();
                //var client2 = service.CreateClient<Resources>();
            }
            catch (Exception exc)
            {
                Console.WriteLine(exc.ToString());
            }
`

**Comment by Sreejithpin** [comment]
Hi
 Please let us know if you are expecting a CreateClient method without any Uri parameter, and can you please explain what are you trying to achieve on this. Thanks

**Comment by UM001** [comment]
So that all configuration is done in the startup file and not need to be registered and injected to be present for the CreateClient().
See this example: https://docs.microsoft.com/en-us/odata/client/using-extensions
