### ISSUE TITLE
OData Connected Service v. 0.11 does not appear in the Connected Service list

### ISSUE THREAD

**Issue by i-TechSoftware** [OData/ODataConnectedService#172]
### Describe the bug
I installed the "OData Connected Service" extension via the Extensions-> Manage Extensions menu (I also tried to download and install the extension from this github repository). After restarting Visual Studio, I tried to make a service by selecting Add -> Connected Service from the project context menu (Net Core 3.1 console app). But it is not on the list of supported services.
At the same time, version 0.10 is normally displayed in the list after installation and allows you to create a proxy class

#### Version of the Project affected
ODataConnectedService v0.11
VisualStudio Version v16.6.2
Microsoft.Odata.Client v7.7.2

#### To Reproduce
1. Install OData Connected Service from marketplace or this repo
2. Restart VS
3. Right click on the project and select Add->Connected Service menu item
4. OData Connected Service not showing in Other Services list

#### Expected behavior
The Connected OData Service extension should appear in the Other Services list

#### Actual behavior
The Connected OData Service extension version 0.11 does not appear in the Other Services list.

#### Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/48829872/96882156-b2553080-1487-11eb-85ef-2a98038a5000.jpg)

**Comment by i-TechSoftware** [comment]
I tried installing the extension at work and at home, but got the same behavior.

**Comment by i-TechSoftware** [comment]
No, there were no errors during installation. I tried installing the extension at work and at home, but got the same behavior.

**Comment by Ardian-i** [comment]
I'm having the same effect since version 0.11.0 too. Please help!

**Comment by unchase** [comment]
@i-TechSoftware @Ardian-i can you tried to remove the Connected service and install it again?

**Comment by i-TechSoftware** [comment]
Yes, I tried it. tried several times ... :)

**Comment by habbes** [comment]
I have not yet managed to reproduce the issue locally, but one reason why VS may fail to load the connected service is if it fails to validate the signatures. I will try to investigate whether there was any error in the signing process.

**Comment by unchase** [comment]
Unfortunately cannot reproduce the issue.

**Comment by Ardian-i** [comment]
> @i-TechSoftware @Ardian-i can you tried to remove the Connected service and install it again?

Yes, I've did that several times but it didn't help. My colleague who was installing today the extension for the first time, had same problem too.

I'm attaching this log file generated by vsix installer. Maybe it could help to find the error:

[dd_VSIXInstaller_20201022225829_5e04.log](https://github.com/OData/ODataConnectedService/files/5425806/dd_VSIXInstaller_20201022225829_5e04.log)

We are using Visual Studio 2019, Version: 16.7.6.

.

**Comment by itsamaik** [comment]
I have the same problem with Visual Studio 2019, Version: 16.5.4

**Comment by marabooy** [comment]
@i-TechSoftware @itsamaik and @Ardian-i We acknowledge the issue and we have figured out that Strong name validation is the current culprit. Kindly downgrade to v.0.10.0 https://github.com/OData/ODataConnectedService/releases/download/v0.10.0/Microsoft.OData.ConnectedService.vsix or disable strong name verification for connected service as we work on a fix. Apologies for the issue.

**Comment by habbes** [comment]
@itsmaik @i-TechSoftware  @Ardian-i  We fixed the issue and pushed v0.11.1 to the marketplace (and to GitHub Releases). Let us know if you experience any issues with this version.

**Comment by i-TechSoftware** [comment]
@habbes Thanks! works correctly
