### ISSUE TITLE
Types emitted on OData client should implement INotifyPropertyChanged interface

### ISSUE THREAD

**Issue by gathogojr** [OData/ODataConnectedService#181]
### Description
OData client uses `DataServiceCollection<T>` to support property tracking.

#### Example:
```csharp
DataServiceCollection<Order> orders = new DataServiceCollection<Order>(dataServiceContext.Orders.Where(d => d.Id == 1));
// Update Amount
orders[0].Amount = 37;
dataServiceContext.SaveChanges();
```
The payload will comprise only of the updated properties and will be sent as a PATCH request:
```
{
    "@odata.type": "#NS.Models.Order",
    "Amount": 37
}
```

However, to use `DataServiceCollection<T>`, the client type needs to implement `INotifyPropertyChanged` interface. The `Order` type for example would look as follows:
```csharp
[Key("Id")]
public partial class Order : BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
{
	public static Order CreateOrder(int ID, DateTimeOffset orderDate, decimal amount)
	{
		Order order = new Order();
		order.Id = ID;
		order.OrderDate = orderDate;
		order.Amount = amount;
		return order;
	}

	public virtual int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			this.OnIdChanging(value);
			this._Id = value;
			this.OnIdChanged();
			this.OnPropertyChanged("Id");
		}
	}
	private int _Id;
	partial void OnIdChanging(int value);
	partial void OnIdChanged();

	public virtual DateTimeOffset OrderDate
	{
		get
		{
			return this._OrderDate;
		}
		set
		{
			this.OnOrderDateChanging(value);
			this._OrderDate = value;
			this.OnOrderDateChanged();
			this.OnPropertyChanged("OrderDate");
		}
	}
	private DateTimeOffset _OrderDate;
	partial void OnOrderDateChanging(DateTimeOffset value);
	partial void OnOrderDateChanged();

	public virtual decimal Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			this.OnAmountChanging(value);
			this._Amount = value;
			this.OnAmountChanged();
			this.OnPropertyChanged("Amount");
		}
	}
	private decimal _Amount;
	partial void OnAmountChanging(decimal value);
	partial void OnAmountChanged();
	/// <summary>
	/// This event is raised when the value of the property is changed
	/// </summary
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
	public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	/// <summary>
	/// The value of the property is changed
	/// </summary>
	/// <param name="propertyName">Property name</param>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
	protected virtual void OnPropertyChanged(string propertyName)
	{
		if (this.PropertyChanged != null)
		{
			this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}
```
**Note:** The class has been stripped to make it less verbose with emphasis being placed on the fragments that support property tracking. Each property setter calls the `OnPropertyChanged(string)` method.

Currently, the client types emitted by OData Connected Service extension do not implement the `INotifyPropertyChanged` interface. An exception is thrown if one tries to use `DataServiceCollection<T>` in OData client.

> System.InvalidOperationException: 'An attempt to track an entity or complex type failed because the entity or complex type 'NS.Models.Order' does not implement the INotifyPropertyChanged interface.'

This in turn makes it impossible to support property tracking and alternatives available result into the whole entity being sent over the wire instead of only the updated properties.

#### Additional context
The CodeGen tool used to emit client types that implement `INotifyPropertyChanged` interface. It'd seem that when a decision was made to discontinue active development of CodeGen, this capability was not migrated to OData Connected Service.

**Comment by gathogojr** [comment]
Turns out that support for property tracking is controlled via a setting on the wizard.
![image](https://user-images.githubusercontent.com/28291332/101129212-3adff880-3612-11eb-8005-968d45dc6c78.png)

To determine if default value for the setting should be `true`.

**Comment by szilardd** [comment]
thanks @gathogojr. this was really helpful.

**Comment by szilardd** [comment]
If a `PreconditionFailed` exception is thrown when calling `SaveChanges`, make sure that you are NOT calling `UpdateObject` before it.

I had something like this:

```cs
foreach (var order in orders)
{
     order.Amount = 1;
     dataServiceContext.UpdateObject(order);
}

dataServiceContext.SaveChanges();
```

The call to `UpdateObject` is not needed.
