### ISSUE TITLE
Tool generates non-compilable code

### ISSUE THREAD

**Issue by pil0t** [OData/ODataConnectedService#191]
### Describe the bug
I created a specific model, with 2 types with the same name, but different namespaces
And both of those Types used in another one, as Collection Item properties.
ConnectedService provide non-compilable code when using both `GenerateMultipleFiles` and `EnableEntityAndPropertyTracking` options at the same time.

#### Version of the Project affected
ODataConnectedService v0.11.1.0
VisualStudio Version v16.5.4

#### To Reproduce
1. Example repository with model https://github.com/pil0t/ExampleForODataConnectedServices
2. Run the application from above
3. Use https://localhost:5001/v1/$metadata  or (https://gist.github.com/pil0t/ebecb6c6aa1a8695e065ecfbdbb395d4)
4. Use metadata from above for generating new ConnectedServiceReference using both `GenerateMultipleFiles` and `EnableEntityAndPropertyTracking` options at the same time.
5. Generation successful
6. Compile

#### Expected behavior
Compile without problem

#### Actual behavior
Getting compile errors: CS0234

#### Screenshots
Added 1 min recording for convenience 
![odataCompileError](https://user-images.githubusercontent.com/820134/103411766-c2be1180-4b82-11eb-9847-9903bb81a236.gif)

#### Additional context
This not happens without both `GenerateMultipleFiles` and `EnableEntityAndPropertyTracking` options at the same time.

**Comment by unchase** [comment]
The same issue when we have the similar named entities with lower and upper case (for example, `Student` and `student`) - only one file for both entities will be created.

**Comment by habbes** [comment]
@pil0t  @unchase I see. Generating multiple files generates a single file per entity type class. The file is named after the entity type without taking the namespace into account. So two entity types with the same name will cause the first file to be overwritten by the first. I guess a workaround for this issue would be to ensure entity names are unique if you are going to generate multiple files, or to just generate the entire code in a single file.

If this is urgent, would you consider contributing a pull request for this? Like including the namespace in file names if a conflict is detected?
