### ISSUE TITLE
Entity tracking does not seem to work in DataServiceContext

### ISSUE THREAD

**Issue by fededim** [OData/ODataConnectedService#192]
I am using VS2019 16.8.3, ODataConnector 0.11.1, I have enabled in the advanced settings "Enable entity and property tracking" and I am trying to update a property on an entity, unluckily context.SaveChanges() does not perform any PATCH call on server.

Here follows the code:

```
var ctx = new SincroADRODataService.Default.Container(new Uri("http://localhost/SincroADR_Api/odata"));
var cam = ctx.Cameras.Where(c => c.Id == 41).Single();
cam.SerialNumber = "12345";
// ctx.UpdateObject(cam);  // explicitly call to force update
ctx.SaveChanges();

```
If I check the ctx.EntityTracker property before SaveChanges it reports 1 entity with the state unmodified and this is strange since it seems that context does not track changes. If I try to explicitly call the context.UpdateObject method passing the entity (e.g. ctx.UpdateObject(cam); ) a PATCH request is performed with the right key value (41), but with a null Delta<Camera> parameter, making the server reject it with bad request since the model is not valid.

Is the code to update a property right ? If yes can someone tell me why the context is not tracking the changed properties ?

**Comment by fededim** [comment]
Found this [old post on client tracking](https://devblogs.microsoft.com/odata/tutorial-sample-client-property-tracking-for-patch/)...it seems that if someone wants to track properties he has to use DataServiceCollection. I changed the code to:

```
                var ctx = new SincroADRODataService.Default.Container(new Uri("http://localhost/SincroADR_Api/odata"));
                var cam = new DataServiceCollection<Camera>(ctx.Cameras.Where(c => c.Id == 41));
                cam[0].SerialNumber = "12345";
                ctx.SaveChanges();
```

This time the ctx.EntityTracker.Entities reports that the entity is modified and the PropertiesToSerialize contains the modified property (e.g. SerialNumber). Then a PATCH request is performed on server with the right id (41) and with the right Delta<Camera>, the request succeeds and data is updated.

**I have however a question: are we forced to use always DataServiceCollection even just for one entity ? Bleah I don't like it at all, it complicates the source. Isn't there a similar method for just one entity ?**

**Comment by habbes** [comment]
Hi @fededim, I believe you need to create a `DataServiceCollection`. The result of `ctx.Cameras.Where` is a `DataServiceQuery<T>` and this class does not automatically observe changes to the entities or add them to the context's entity tracker. So you can either use a `DataServiceCollection` or you can manually add objects to the context's entity tracker by calling `context.AttachTo(cam[0])`.
