### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by adrien-constant** [OData/ODataConnectedService#199]
### Describe the bug
With the latest version of the extension, it is not possible to add a connected service. The modal form is stucked on the second step. The same scenario is working with version 0.10.0 (Microsoft.OData.Client v7.6.3.10130)

#### Version of the Project affected
ODataConnectedService v0.11.1
Visual Studio 2019 Enterprise Version v16.8.2

#### To Reproduce
1. Add a new connected service
2. In the 'Address' field, browse for a XML Metadata file
3. Click 'Next' to go to the 'Scheme Types Selection' tab
4. Click 'Next' to go to the 'Function/Action Imports Selection' tab

#### Expected behavior
The 'Function/Action Imports Selection' tab is displayed.

#### Actual behavior
Nothing happens.
Clicking on 'Finish' does nothing either.
Clicking on 'Cancel' then displays an exception :

![image](https://user-images.githubusercontent.com/3390053/108059911-78bbbd00-7056-11eb-95b6-d4ef950ea9d3.png)

System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: key&#x000D;&#x000A;   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)&#x000D;&#x000A;   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue&amp; value)&#x000D;&#x000A;   at Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(IEnumerable`1 referencedModels, Boolean includeDefaultVocabularies, IEdmModel&amp; model, IEnumerable`1&amp; parsingErrors)&#x000D;&#x000A;   at Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(XmlReader reader, Boolean ignoreUnexpectedAttributesAndElements, IEdmModel&amp; model, IEnumerable`1&amp; errors)&#x000D;&#x000A;   at Microsoft.OData.ConnectedService.Common.EdmHelper.GetEdmModelFromFile(String path, ConnectedServiceContext context)&#x000D;&#x000A;   at Microsoft.OData.ConnectedService.ODataConnectedServiceWizard.SchemaTypeSelectionViewModel_PageLeaving(Object sender, EventArgs args)&#x000D;&#x000A;   at Microsoft.OData.ConnectedService.ViewModels.SchemaTypesViewModel.&lt;OnPageLeavingAsync&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.ConnectedServices.ViewModel.ConfigureProviderWizardViewModel.&lt;NotifyOnPageLeavingAsync&gt;d__38.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.ConnectedServices.ViewModel.ConfigureProviderWizardViewModel.&lt;&gt;c__DisplayClass39_0.&lt;&lt;TrySetCurrentEntryAsync&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.ConnectedServices.ViewModel.ConfigureProviderWizardViewModel.&lt;TryNavigatingAsync&gt;d__40.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.ConnectedServices.ViewModel.ConfigureProviderWizardViewModel.&lt;TrySetCurrentEntryAsync&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.ConnectedServices.ViewModel.ConfigureProviderWizardViewModel.&lt;&lt;NextImplementation&gt;b__34_0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.&lt;&gt;c__DisplayClass35_0.&lt;&lt;FileAndForget&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by unchase** [comment]
Hi, @adrien-constant
Fixed in PR #178
Waiting in the next release.

**Comment by adrien-constant** [comment]
> Hi, @adrien-constant
> Fixed in PR #178
> Waiting in the next release.

Thank you @unchase . Is there any estimated release date ?

**Comment by unchase** [comment]
> > Hi, @adrien-constant
> > Fixed in PR #178
> > Waiting in the next release.
> 
> Thank you @unchase . Is there any estimated release date ?

@gathogojr ?

**Comment by gathogojr** [comment]
@habbes ?

**Comment by habbes** [comment]
@adrien-constant  @unchase we'll have a release within this week.

**Comment by unchase** [comment]
> @adrien-constant @unchase we'll have a release within this week.

Nice. Thx!

**Comment by habbes** [comment]
@adrien-constant @unchase new version (0.12.0) has been released. Kindly verify whether it solves your issue.

**Comment by adrien-constant** [comment]
That's fixed, thanks.
