### ISSUE TITLE
ConnectedService.json CustomHttpHeaders is not used.

### ISSUE THREAD

**Issue by dr-consit** [OData/ODataConnectedService#215]
### Describe the bug
When loading `ConnectedService.json` the value from `CustomHttpHeaders` is ignored.
When generating `ConnectedService.json` `CustomHttpHeaders` are not written.

#### Version of the Project affected
ODataConnectedService v0.12.1
VisualStudio Version v16.8.5
Microsoft.Odata.Client v7.8.2

#### To Reproduce
1. Add connected service,
2. Check "Include Custom Http Headers"
3. Fill in a value in "Custom Headers"
4. Click finish.
5. Open the generated "ConnectedService.json"
6. Observe that `CustomHttpHeaders` is blank.
7. Write a value in `CustomHttpHeaders` and make sure `IncludeCustomHeaders` is `true`
8. Add connected service,
9. Click "Load Settings Config file"
10. Observe that "Include Custom Http Headers" is checked but the value from `CustomHttpHeaders` is not loaded.

#### Expected behavior
Value in `CustomHttpHeaders` in `ConnectedService.json` file should be used and updated.

#### Actual behavior
Value in `CustomHttpHeaders` in `ConnectedService.json` is neither written nor read.

**Comment by marabooy** [comment]
Currently this is by design as the headers may contain secrets or tokens and we didn't wan't to store headers and web proxy details to the JSON file.

**Comment by dr-consit** [comment]
I don't really see how this is the responsibility of this extension. Many things may contain secrets, the URL for example may contain an API key or something similar.
But even if you decide that it is your responsibility, to baby the user so they don't have secrets stored, I don't see why you can't load these values if they are already present in the file - that is in the "Load Settings Config file" functionality.

**Comment by marabooy** [comment]
Hi @dr-consit we have Identified this as a feature gap and would like to invite contributions if you are able. At the same time it would be great to have users opt-in to the new behaviour and alerting them when these items are being saved. Do let me know if you need any help if you would like to contribute to this feature.

**Comment by dr-consit** [comment]
OK, I've created a Pull Request: #216
