### ISSUE TITLE
Selecting specific schemas for code generation

### ISSUE THREAD

**Issue by lscorcia** [OData/ODataConnectedService#219]
#### Is your feature request related to a problem? Please describe.
We are migrating a number of logic libraries to .net standard, planning a future migration to .net 5. Many of those read or write data to different SP2013 on-premises sites using CSOM, which is not available for .net standard. As we only use basic data access, we are trying to rewrite those operations using OData access to SharePoint lists. It works pretty well, but the generated code files and proxy classes are huge and after generating code for five-six sites, Visual Studio grinds more and more.
Since we only need the `SP.Data` schema from the >10 that are exposed from SP `$metadata` endpoint, it would be helpful to add a feature to limit code generation to specified schemas only.

#### Describe the solution you'd like
I would like to have an user-editable list of schema namespaces to explicitly include in code generation.

#### Describe alternatives you've considered
Well, the alternative is to hand-edit the generated schemas, or not use any generated class and handcraft the OData access layer.
I am not sure if this feature is already present for OData 4 (there is a tab called "Schema Types Selection" that seems like it could be useful), but it does not populate with elements for SP2013 metadata, and it seems there is no way to specify schemas manually:

![immagine](https://user-images.githubusercontent.com/16761934/118334724-6db9e100-b50e-11eb-9f9e-300404018c80.png)

#### Additional context
I have enabled JSONLight on my SP2013 instance.
Please note that SharePoint 2013 on-premises is ancient, this is the edmx header it presents:

![immagine](https://user-images.githubusercontent.com/16761934/118334648-4cf18b80-b50e-11eb-9226-9e8ef18e1273.png)

**Comment by habbes** [comment]
Hi @lscorcia, OData Connected Service has a feature to select which schema types to include in the generated code as well as the ability to split the generated code into multiple files. However, these features are only available for OData v4 services. There are currently no plans to provide these features for v1-v3 services.
