### ISSUE TITLE
Invalid class name generated

### ISSUE THREAD

**Issue by Remo** [OData/ODataConnectedService#224]
### Describe the bug

When generating the C# classes, I get a few invalid names like `MxnConfValCopyValues$` . The `$` isn't a valid character for a class name.

#### Version of the Project affected
ODataConnectedService v0.12.1
VisualStudio Version v16.8.4
Microsoft.Odata.Client v7.9.0

#### To Reproduce

Create an odata service with a `$` in the name of a type

```xml
<ComplexType Name="MxnConfValCopyValues$">
   <Property Name="ModifiedSource" Type="IfsApp.MxnCar.MxnConfVal"/>
</ComplexType>
```

and then a function like this:

```xml
<Function Name="MxnConfVal.DefaultCopy" IsBound="true">
   <Parameter Name="MxnConfVal" Type="IfsApp.MxnCar.MxnConfVal" Nullable="false"/>
   <Parameter Name="CopyValues" Type="IfsApp.MxnCar.MxnConfValCopyValues$"/>
   <ReturnType Type="IfsApp.MxnCar.MxnConfVal"/>
</Function>
```

#### Expected behavior

A working class

#### Actual behavior

An invalid class and code that doesn't compile.

#### Screenshots

![image](https://user-images.githubusercontent.com/129864/124776500-c8385200-df3f-11eb-9abe-d619884a7fcc.png)

**Comment by SomeTroglodyte** [comment]
Or try a "-" in a field name - fails.

**Comment by SomeTroglodyte** [comment]
The code does not do any sanitizing on Edm metadata before writing it into generated identifiers, specifically IEdmNamedElement.Name is only "fixed" if it matches a target language identifier verbatim, unless it is massaged anyway (e.g. prefixing "_" for a backing field name). Except if this.context.EnableNamingAlias is on, in which case it's passed through Customization.CustomizeNaming.

I have no idea how to turn on EnableNamingAlias or provide a CustomizeNaming implementation to sanitize Edm names to valid identifier names in the GUI, I suspect that's not what it's for.

So I suggest creating a sanitizing function that reduces an arbitrary string to a valid target language identifier and call it in the vicinity of all ~40 references to CustomizeNaming, even _on_ the output of CustomizeNaming. Might get tricky if the Name in question does not contain _any_ character valid in identifiers and the language does not offer identifer escaping... (like `[arbitrary field name]` in SQL or <code>&#96;...funny name 😂...&#96;</code> in kotlin or...).
