### ISSUE TITLE
Make ODataConnectedService feature available in VS2022

### ISSUE THREAD

**Issue by joaofpereira** [OData/ODataConnectedService#225]
### Make ODataConnectedService feature available in VS2022
With the release of the preview version of Visual Studio 2022, my company wants to switch to that version because VisualStudio 2019 is highly unproductive because of the memory limitations of 32-bit application.
To do that, we need the tool ODataConnectedService to be available on that VS version.
We tried to install the .vsix but t doesn't recognize the VS2022.

Is there any way you provide to the community such installer?
It would be very good to start working on a 64-bit application as soon as possible.

Thank you.
João Pereira

**Comment by AllTaken** [comment]
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by mobenn** [comment]
We are still waiting??? :)

**Comment by j-dc** [comment]
Is there a possibility, wouldn't it be easier, to provide a T4-template version only..   without any fancy GUI?

**Comment by GoranHalvarsson** [comment]
Yes please, any update ?

**Comment by pbru87** [comment]
I guess that is the current status: https://github.com/OData/ODataConnectedService/pull/239

**Comment by GoranHalvarsson** [comment]
I see. Let's hope there will be one soon :-)

**Comment by 1Jesper1** [comment]
Would be great!

**Comment by etaxi341** [comment]
Any news on this?

**Comment by mibmal** [comment]
Any news?

**Comment by Odraio** [comment]
@etaxi341 @mibmal I started using [Unchase.Odata.Connectedservice](https://github.com/unchase/Unchase.Odata.Connectedservice) in VS 2022. Works great! (It is noted in the Microsoft documentation as well: [Code-Generation-Tool](https://docs.microsoft.com/en-us/odata/client/code-generation-tool)

**Comment by etaxi341** [comment]
> @etaxi341 @mibmal I started using [Unchase.Odata.Connectedservice](https://github.com/unchase/Unchase.Odata.Connectedservice) in VS 2022. Works great!
> 
> (It is noted in the Microsoft documentation as well: [Code-Generation-Tool](https://docs.microsoft.com/en-us/odata/client/code-generation-tool))

Thanks for the info. I sadly already tried that and it does not like huge odata interfaces like the one from Dynamics 365

**Comment by benbward** [comment]
> Thanks for the info. I sadly already tried that and it does not like huge odata interfaces like the one from Dynamics 365

I'm also in need of a client proxy for the D365 beast.  Have you come up with any working solutions?  I'm currently testing dotnet-odata4 but can't yet recommend it.

**Comment by etaxi341** [comment]
@benbward  
> I'm also in need of a client proxy for the D365 beast. Have you come up with any working solutions? I'm currently testing dotnet-odata4 but can't yet recommend it.

I have put the oData stuff in a new project that is in the same solution. I open that project with VS 2019 and have a precompiler statement, that makes the project .net5 in VS2019 and .net6 in VS2022.

I hate this workaround but I could not think of any other.

**Comment by ngelotte** [comment]
@etaxi341 Would you mind sharing info about your precompliler statement? I am in the same unfortunate situation with D365.

**Comment by etaxi341** [comment]
@ngelotte 

This is what i edited in my csproj:

```
<PropertyGroup Condition="'$(VisualStudioVersion)' != '16'">
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <Platforms>AnyCPU;x64</Platforms>
    <LangVersion>latest</LangVersion>
</PropertyGroup>
  
<PropertyGroup Condition="'$(VisualStudioVersion)' == '16'">
    <TargetFrameworks>net472;net5.0</TargetFrameworks>
    <Platforms>AnyCPU;x64</Platforms>
    <LangVersion>latest</LangVersion>
</PropertyGroup>
```

VisualStudioVersion 16 is VS 2019 and 17 (or in my case anything that is not 16) is VS 2022

**Comment by 1Jesper1** [comment]
Not merged yet, but here is the VSIX for 2022 [https://github.com/1Jesper1/ODataConnectedService-For-VS2022/raw/151aa1f2ffacb1881acd4d9b8fdc595a5569e083/src/ODataConnectedService/Microsoft.OData.ConnectedService.vsix](https://github.com/1Jesper1/ODataConnectedService-For-VS2022/raw/151aa1f2ffacb1881acd4d9b8fdc595a5569e083/src/ODataConnectedService/Microsoft.OData.ConnectedService.vsix) from PR https://github.com/OData/ODataConnectedService/pull/274 Use at your own risk!

**Comment by github6043** [comment]
Hi 1Jesper1, downloaded the *.vsix several times an get allways when trying to install

5/29/2022 11:18:22 PM - Microsoft VSIX Installer
5/29/2022 11:18:22 PM - -------------------------------------------
5/29/2022 11:18:22 PM - Initializing Install...
5/29/2022 11:18:22 PM - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package. ---> System.IO.FileFormatException: File contains corrupted data.

**Comment by 1Jesper1** [comment]
> Hi 1Jesper1, downloaded the *.vsix several times and get allways the following error when trying to install
> 
> 5/29/2022 11:18:22 PM - Microsoft VSIX Installer 5/29/2022 11:18:22 PM - ------------------------------------------- 5/29/2022 11:18:22 PM - Initializing Install... 5/29/2022 11:18:22 PM - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package. ---> System.IO.FileFormatException: File contains corrupted data.

Thanks, I see the problem. Please try https://github.com/1Jesper1/ODataConnectedService-For-VS2022/releases/tag/v0.14.0

**Comment by cilerler** [comment]
@Sreejithpin, I'm wondering what thought process you had when you labeled this issue as `P3`? 
I mean, the request in this issue is an essential piece that allows developers to make clients easily connect and consume the OData endpoint. How come it is justified as something that can wait? Would you please elaborate on it? Thanks in advance.

**Comment by 1Jesper1** [comment]
I see a new PR has been created: https://github.com/OData/ODataConnectedService/pull/295

**Comment by EdwinRono-254** [comment]
We are trying to consume BC200 OData V4  in Visual Studio 2022 but ODataConnectedService feature is not able. Is there a posibility of enabling this feature soon?

**Comment by cilerler** [comment]
@EdwinRono-254 use the CLI

```powershell
dotnet tool install --global Microsoft.OData.Cli;
odata-cli generate -m "https://localhost:5001/odata/$metadata" -o "./Connected Services/OData Service";
```

**Comment by luizs81** [comment]
> Not merged yet, but here is the VSIX for 2022 https://github.com/1Jesper1/ODataConnectedService-For-VS2022/releases/tag/v0.14.0 from PR #274 Use at your own risk!

Downloaded, installed on my VS2022 and it's working like a charm. I hope someone can make an official release from it.

**Comment by 1Jesper1** [comment]
Nice @luizs81 There is an official release based on another PR https://github.com/OData/ODataConnectedService/releases/tag/v1.0.0

**Comment by fgosik** [comment]
Hello everyone,
 I have a problem with the 2022 version, when I want to use it with Finance and operations, I have errors in the name of some objects, here Assigned position
[global::Microsoft.OData.Client.OriginalNameAttribute("Assigned position")]
public virtual global::Microsoft.Dynamics.DataEntities.PositionV2Single Assigned position
Have you ever encountered this kind of problem?

**Comment by EdwinRono-254** [comment]
> Hello everyone,
> I have a problem with the 2022 version, when I want to use it with Finance and operations, I have errors in the name of some objects, here Assigned position
> [global::Microsoft.OData.Client.OriginalNameAttribute("Assigned position")]
> public virtual global::Microsoft.Dynamics.DataEntities.PositionV2Single Assigned position
> Have you ever encountered this kind of problem?

Are you trying to consume Finance & Operations OData Web Service or SOAP Web Service?

**Comment by fgosik** [comment]
> > Hello everyone,
> > I have a problem with the 2022 version, when I want to use it with Finance and operations, I have errors in the name of some objects, here Assigned position
> > [global::Microsoft.OData.Client.OriginalNameAttribute("Assigned position")]
> > public virtual global::Microsoft.Dynamics.DataEntities.PositionV2Single Assigned position
> > Have you ever encountered this kind of problem?
> 
> Are you trying to consume Finance & Operations OData Web Service or SOAP Web Service?

After the generation, I made a replace of the spaces on the names of objects that were causing problems. Now it works, but I will lose my changes if changes are made in finance and operations.

**Comment by ElizabethOkerio** [comment]
Check out the latest release https://marketplace.visualstudio.com/items?itemName=marketplace.ODataConnectedService2022

**Comment by bisaga** [comment]
> public virtual global::Microsoft.Dynamics.DataEntities.PositionV2Single Assigned position
This is still happening, the generated code contains names with spaces, the latest version didn't solve it.

**Comment by ChrisSchaller** [comment]
The templates in that connected service package have not been updated to actually _work_ in a clean vs 2022 environment. This combination of dependencies will only work is you have a previous installation of VS 2019:

```
<#/*
//----------------------------------------------------------------------------------
// <copyright file="ODataT4CodeGenFilesManager.ttinclude" company=".NET Foundation">
//      Copyright (c) .NET Foundation and Contributors.  All rights reserved. 
//      See License.txt in the project root for license information.
// </copyright>
//---------------------------------------------------------------------------------
*/#><#@ assembly name="System.Core.dll"
#><#@ assembly name="System.Xml.dll"
#><#@ assembly name="EnvDTE.dll"
#><#@ assembly name="Microsoft.OData.ConnectedService.dll"
#><#@ assembly name="Microsoft.VisualStudio.ConnectedServices.dll"
#><#@ assembly name="System.Xml.Linq.dll"
#><#@ assembly name="Microsoft.OData.CodeGen.dll"
```

Does anyone have any guidance on the required updates to get this to work? I can guess that we need to reference the new `Microsoft.OData.ConnectedService.VS2022Plus.dll` but not sure about the rest yet.

**Comment by denisulmer** [comment]
Is OData dead from a Microsoft perspective? I ask because I would like to implement it, but if that is the state of support I will go and use GraphQL instead.

**Comment by ChrisSchaller** [comment]
> Is OData dead from a Microsoft perspective? I ask because I would like to implement it, but if that is the state of support I will go and use GraphQL instead.

Not sure this is the right space for such a comment, I'm personally very happy with it and get a lot of support on issues through this and other forums. My OData use cases are different to my GraphQL environments and I tell you I much perfor to code with OData over graph. It is however a Community project and this issue is closed and as such will not likely get much visibility If you have specific feedback or have also experienced this issue, post in here and I'll polish up my PR that deals with this.

**Comment by dotnetero** [comment]
> Is OData dead from a Microsoft perspective? I ask because I would like to implement it, but if that is the state of support I will go and use GraphQL instead.

https://devblogs.microsoft.com/odata/the-future-of-odata-odata-nxt/

**Comment by onyangofred** [comment]
Not merged yet, but here is the VSIX for 2022 
https://github.com/1Jesper1/ODataConnectedService-For-VS2022/releases/tag/v0.14.0 from PR https://github.com/OData/ODataConnectedService/pull/274 

Use at your own risk (USISEME HAUKUONYWA)!

Downloaded, installed on my VS2022 and it's working like a charm. I hope someone can make an official release from it.
