### ISSUE TITLE
Any plans to make it work in VS 2022?

### ISSUE THREAD

**Issue by fscopel** [OData/ODataConnectedService#231]
Just wondering if there are plans to make it work with VS 2022?

**Comment by ImGonaRot** [comment]
This is a duplicate of #225

**Comment by habbes** [comment]
Hi @fscopel  @ImGonaRot we do plan to add support for VS2022, we'll update this thread when we have an ETA.

**Comment by julealgon** [comment]
@habbes do you have any updates to share here?

**Comment by ElizabethOkerio** [comment]
Check out the latest release https://marketplace.visualstudio.com/items?itemName=marketplace.ODataConnectedService2022
