### ISSUE TITLE
ODATA Connected Service Advanced Settings "GenerateMultipleFiles" option is missing

### ISSUE THREAD

**Issue by jasonrichardcraig** [OData/ODataConnectedService#240]
The generate multiple files option is not available in the v0.13.0 Settings UI but there is an entry in the ConnectedService.json settings file.

I tried editing the settings file manually and forcing an update but it did not work.

ODataConnectedService v0.13.0
VisualStudio Version v15.9.37

1. Create new project in VS
2. Add connected service to project
3. Click the advanced settings

Check box to select the generate multiple files option is missing from the UI.

I tried installing v0.12.0 and v0.9.0 but the UI was the same as the v0.13.0 UI

Screen Shots: https://stackoverflow.com/questions/70336441/odata-connected-service-advanced-settings-generatemultiplefiles-option-is-miss

**Comment by habbes** [comment]
Hi @jasonrichardcraig that option is only available if you're targeting an OData v4 service. Are you targeting and OData v1-v3 service by any chance?

**Comment by jasonrichardcraig** [comment]
Yes it is a v2 service, I verified the option appears for v4 services.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by habbes** [comment]
@jasonrichardcraig thanks for confirming. We will update our docs to reflect this. There are currently no plans to provide that feature for OData v1-v3 services.
