### ISSUE TITLE
[T4] OData v4 Client Code Generator generates a  C# proxy class that won’t compile if the model contains an Entity that has a property with name "Context"

### ISSUE THREAD

**Issue by LaylaLiu** [OData/ODataConnectedService#242]
BaseEntityType contains a property named "Context".

So when a model contains an entity which has a property named "Context". The client generated code will be like 

public partial class Product : global::Microsoft.OData.Client.BaseEntityType
{
            ...
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Context")]
        public global::System.Collections.ObjectModel.ObservableCollectionglobal::OutlookApiBetaModel.CustomProperty Context
        {
            get            {                ...            }
            set            {                ...            }
        }

This will lead to "ConsoleApplication7.Product.Context' hides inherited member 'Microsoft.OData.Client.BaseEntityType.Context'. Use the new keyword if hiding was intended. “

**Comment by mikepizzo** [comment]
We probably should have named these internal properties such that they had a lower chance of conflicting with user properties.  i.e., "__context" or some such.
