### ISSUE TITLE
Multiple Connected Services in one Project

### ISSUE THREAD

**Issue by MarkusWolf87** [OData/ODataConnectedService#245]
Hi,

is it possible to add more than one odata endpoint to a visual studio project.

If I added an odata endpoint via connected service extension in visual studio and is not possible to add a new one. Only to config the endpoint is possible. Thanks.

**Comment by habbes** [comment]
Hi @MarkusWolf87, yes it's possible to add multiple client proxies using the OData Connected Service extension in Visual Studio. Each service will get a folder under the `Connected Services` folder where the corresponding generated code will be stored. To avoid any conflicts, you should ensure different namespaces are used when configuring the wizard. If the services already have different namespaces, this should generally not be an issue.
