### ISSUE TITLE
odata-cli is ignoring internal option generation

### ISSUE THREAD

**Issue by artur-moreira** [OData/ODataConnectedService#268]
I'm assuming naming mismatch affected the expected behavior.

Property definition:
https://github.com/OData/ODataConnectedService/blob/master/src/Microsoft.OData.Cli/GenerateOptions.cs#L51

Command definition:
https://github.com/OData/ODataConnectedService/blob/master/src/Microsoft.OData.Cli/GenerateCommand.cs#L86

**Comment by artur-moreira** [comment]
https://github.com/OData/ODataConnectedService/blob/master/src/Microsoft.OData.Cli/GenerateCommand.cs#L82

changing this line to "enable-internal" solves the issue

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/ODataConnectedService/pull/392. @artur-moreira - Please test to verify
