### ISSUE TITLE
odata-cli custom header not used when fetching metadata

### ISSUE THREAD

**Issue by Remo** [OData/ODataConnectedService#272]
### Describe the bug

I'm trying to create OData classes using the new CLI (great idea, I love it). My service is protected and thus needs a custom header. This includes the metadata call, not only the actual call to execute the request!

#### Version of the Project affected
Microsoft.OData.Cli v0.1.0

#### To Reproduce

Cal the CLI generate command for a service protected by a custom header.

```odata-cli.exe generate -m "https://my-server/my-service/$metadata" -o output --multiple-files -h Authorization:"Basic ......." -ns "service.ns" -fn "Odata"```

#### Expected behavior

No `The remote server returned an error: (401) Unauthorized.`

#### Actual behavior

`The remote server returned an error: (401) Unauthorized.`

#### Additional context

I've had a look, it seems like the custom headers aren't used here. The webRequest uses proxy and everything, but here the custom header isn't used:
https://github.com/OData/ODataConnectedService/blob/master/src/Microsoft.OData.CodeGen/Common/MetadataReader.cs#L51-L69

Is there a reason why the custom headers aren't used there?

**Comment by Nthemba** [comment]
This issue is fixed by PR #311
