### ISSUE TITLE
Date format error on DefaultValue

### ISSUE THREAD

**Issue by zulander1** [OData/ODataConnectedService#301]
I have this error when importing:

(0,0) : error 0054: Default value (/Date(1577833200000)/) is not valid for DateTime. The value must be in the form 'yyyy-MM-dd HH:mm:ss.fffZ'.

the property is : <Property Name="startDateInUTC" Type="Edm.DateTime" Nullable="true" sap:required="false" sap:creatable="true" sap:updatable="true" sap:upsertable="true" sap:visible="true" sap:sortable="true" sap:filterable="true" sap:display-format="Date" **DefaultValue="/Date(1577836800000)/"** sap:label="Start Date"/>

Thank;s

**Comment by mikepizzo** [comment]
As per the error code, this appears to be an invalid datetime format being returned from the service for the DefaultValue.

**Comment by zulander1** [comment]
> As per the error code, this appears to be an invalid datetime format being returned from the service for the DefaultValue.

Is it allowed to have date(???) as a default value, I am no expert it's directly form SAP SuccessFactors api edmx

**Comment by mikepizzo** [comment]
The default value should be a valid DateTime literal value, such as "0001-02-01 19:49:43"

**Comment by mikepizzo** [comment]
I've followed up with SAP to see if we can get the service metadata fixed.  In the meantime, a workaround could be to download the metadata, remove the default value, and then generate the proxy classes from that downloaded file.
