### ISSUE TITLE
odata-cli generated entities aren't `ObservableCollection`

### ISSUE THREAD

**Issue by a98c14** [OData/ODataConnectedService#313]
### Describe the bug
When odata client is generated through odata-cli tool, created entities are generated as `Collection` instead of `ObservableCollection` but when it is generated through Visual Studio OData extension they are generated as `ObservableCollection`. Some parts of our code was relying on it being `Observable`. Could it be possible to have an option for the odata-cli tool that generates `ObservableCollection` instead of regular `Collection` ?

#### To Reproduce

Generate client file using Visual Studio extension and another one with odata-cli tool and compare the results

#### Screenshots

<img width="1846" alt="image" src="https://user-images.githubusercontent.com/6324924/186262013-c070d41c-b415-439d-be44-206b5d5e3e94.png">

On the left we have odata-cli generated class and on the right we have a file that is generated by VisualStudio

**Comment by gregwinterstein** [comment]
This issue is fixed in #330 with the `enable-tracking` option
