### ISSUE TITLE
Dynamics 365 OData metadata contains spaces causing OData generated code to fail compilation

### ISSUE THREAD

**Issue by pmkevans** [OData/ODataConnectedService#317]
The issue is described here: https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/463165/odata-properties-have-spaces
In short, current versions of D365 have spaces in some property names.  OData-CLI is generating class and variable names using this information without managing the spaces and thereby generating code that does not compile.

Although the root cause is D365 being noncompliant it would be sensible for ODataConnectedService to have smarter name generation to validate that all names generated are valid C# identifiers.

**Comment by mikepizzo** [comment]
We could add logic to the class generation (i.e., to replace space with underscore) but that could be ambiguous (i.e., if the store had the same property name in one case with a space and in one case without a space).  We could add additional handling for that case, or even just consider it an edge case and "better than what we have now", however, generating the types with properties that don't contain a space is just a small step in what is going to be a much bigger issue, which is the fact that the ODataClient (or any other client using the classes) is going to have to create URLs to query the service, and read/bind responses to the types, and all of the underlying libraries for handling OData Urls and payloads aren't going to be able to deal with property names that contain spaces.

**Comment by sanderson196** [comment]
As a follow up to the initial Feature request, I have (manually) modified the generated c# code to remove the spaces from the generate method names and where they are used but not removing the spaces from code related to the original Odata Endpoints.  For example, ((this._Template Tasks == null)) is converted to ((this._TemplateTasks == null)) but Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.ProcessTemplateTask>(GetPath("Template tasks")); remains the same.

Once done you get compliable and usable code that appears to still be able to access the OData endpoints properly.  I encourage the community to verify my results.

For reference, I use a regex search to find and replace the "offending" c# code
(?<!")Template tasks(?!")

**Comment by magiva** [comment]
has there been any progress on a fix for this ? who owns the issue here? as microsoft introduced the issue and isnt this tool also microsofts ?

**Comment by magiva** [comment]
do you have any links to the process you used or did you just use regex to replace the space with _ or remove etc ?

**Comment by sanderson196** [comment]
Just used Regex for search for and replace.  The catch is that you can't change the data between quotes (the reference to Dynamcis) but only change the code function references.  Therefore your regex has to exclude items that start and end in "

Scott Anderson
IT Manager


Mobile: +1 9192916265   |  Phone: 919.804.6331
Email: ***@***.******@***.***>
501 Innovative Way | Zebulon, NC 27597 | USA
[https://i.imgur.com/15N3tZu.png]<https://noelgroup.net/>

**Comment by magiva** [comment]
yeah that was our thoughts also, many thanks for the reply, much appreciated

**Comment by AndreasHassing** [comment]
This has recently been fixed in Dynamics for App 10.0.32 and has been backported to 10.0.30 and 10.0.31.

To find the backport in LCS use this issue #: 753226

**Comment by magiva** [comment]
thanks for the update, will test soon

**Comment by dazinator** [comment]
> This has recently been fixed in Dynamics for App 10.0.32 and has been backported to 10.0.30 and 10.0.31.
> 
> To find the backport in LCS use this issue #: 753226


I am new to LCS. We have a partner account, and an environment with an existing deployment for dev purposes. 
What does this mean: 

> To find the backport in LCS use this issue #: 753226

I can't see anywhere to search by issue number exactly - how does this help upgrade a deployment?

**Comment by AndreasHassing** [comment]
@dazinator see [this documentation](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/issue-search-lcs) on how to search the LCS issue database.

See [this](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/install-metadata-hotfix-package?source=recommendations) on how to apply a hotfix to your development environment 😊.

**Comment by dazinator** [comment]
@AndreasHassing thank you much obliged!

**Comment by AndreasHassing** [comment]
> Still broken in public VS extension 1.0.1

This is not an issue with the extension per se, but rather a bug in FnO. As mentioned above, there are hotfixes to solve this on regressed versions.

**Comment by AndreasHassing** [comment]
> [FnO???](https://en.wikipedia.org/wiki/FNO) Whatever it is, this is also a plain Visual Studio extension and the official Microsoft answer to consuming OData from .net code. No Dynamics365 involved at all. So any Dynamics365-Specific kludge is irrelevant as long as the basic code fails to map a subset of allowed names. Don't get me wrong - I'm actually kind of glad about it as it saves me a bunch of work and I can tell the other departments "sorry not my fault" 😸

The bug saves you from doing work? Ok 😀👌.

Anyhow. I imagine the maintainers would prefer a new Issue since this one is primarily for the issue coming from Dynamics 365's OData entity types.

Also, consider adding some more details about what _your_ issues are-- especially considering they are not related to Dynamics.

**Comment by adamsilenko** [comment]
It is still issue in 1.0.4 version...
I made a PowerShell script to find & fix generated .cs files. It replace spaces in the names to underline char.

```
function badNameFix() {
	#declare $entitySetsFolder (with generated .cs files) and $badNameFolder (destination to backup oryginal files)
	$badNamePattern = "^\s*(public virtual global::|private global::|partial )((\w+\.)*\w+(<[^>]+>)?)\s(?'name'\w+( \w+)+)\s*(\([^\)]*\))?;?\s*$"

	# Ensure the destination directory exists
	if (!(Test-Path -Path $badNameFolder)) {
		New-Item -ItemType directory -Path $badNameFolder
	}
	$totalFiles = 0
	$totalNames = 0
	# Iterate over all .cs files in the search directory
	Select-String -Path "$entitySetsFolder\*.cs" -Pattern $badNamePattern | Group-Object -Property Filename | ForEach-Object {
		$fileName = $_.Name 
		Write-Output "File with bad definitions: $fileName"
		$badNames = $_.Group.Matches | ForEach-Object { $_.Groups["name"].Value } | Sort-Object -Descending

		# Read the file content
		$content = Get-Content -Path "$entitySetsFolder\$fileName" -Raw

		foreach($badName in $badNames) {
			$totalNames++
			$corectName = $badName -replace ' ', '_'
			Write-Output "Changing: $badName >> $corectName"
			# Replace the pattern with the replacement string
			$content = $content -creplace "(?<!"")$badName(?!"")", $corectName
		}
		# Move & rename the file to the destination directory
		Move-Item -Path "$entitySetsFolder\$fileName" -Destination "$badNameFolder\$fileName.old"
		# Write the new content to the file
		Set-Content -Path "$entitySetsFolder\$fileName" -Value $content
		$totalFiles++
	}
	Write-Output "Finished. $totalNames names was changed in $totalFiles files."
}
```
