### ISSUE TITLE
Argument list too long: odata-cli

### ISSUE THREAD

**Issue by ogysha** [OData/ODataConnectedService#327]
### I'm trying to generate proxy classes from a pretty big ERP OData endpoint, and the tool fails with the error: `argument list too long: odata-cli`

I've created a pipe of commands to exclude all types but one, and it is valid but fails due to a great amount of `-est` argument length.
```
$ odata-cli generate -m "https://.....dynamics.com/data/" -o "." -fn "ERPODataClient" -ucc -iue -est "$(cat ConnectedService.json | jq '.ExtendedData.ExcludedSchemaTypes' | sed '1d;$d' | sed 's/[ "]//g' | awk -v d="" '{s=(NR==1?s:s d)$0}END{print s}')" -ebo "$(cat ConnectedService.json | jq '.ExtendedData.ExcludedBoundOperations' | sed '1d;$d' | sed 's/[ "]//g' | sed 's/(.*//g' | sed 's/$/,/g' | awk -v d="" '{s=(NR==1?s:s d)$0}END{print s}'TypeV2)"
```

#### If I add in the pipe `head -n 100` to limit to 100 lines which I concatenate into `-est` and `-ebo` argument, then all is okay.
```
odata-cli generate -m "https://foo-test.sandbox.operations.dynamics.com/data/" -o "." -fn "ERPODataClient" -ucc -iue -est "$(cat ConnectedService.json | jq '.ExtendedData.ExcludedSchemaTypes' | sed '1d;$d' | sed 's/[ "]//g' | head -n 100 | awk -v d="" '{s=(NR==1?s:s d)$0}END{print s}')" -ebo "$(cat ConnectedService.json | jq '.ExtendedData.ExcludedBoundOperations' | sed '1d;$d' | sed 's/[ "]//g' | sed 's/(.*//g' | sed 's/$/,/g' | head -n 100 | awk -v d="" '{s=(NR==1?s:s d)$0}END{print s}'TypeV2)"
```

**Comment by mtherien** [comment]
+1 Creative workaround.

**Comment by AndreasHassing** [comment]
Would an option like: `--included-schema-types` work better?

It would turn the set of entities included for generation upside down, so it would be a mutually exclusive option with the exclusion list and only generate data types for the listed entries?

I feel like at least for Dynamics with some 3k+ entity sets, it makes sense to inverse the logic 😊.

**Comment by ogysha** [comment]
That would be a perfect solution! I would like to contribute to this one by creating a PR for it.

**Comment by ElizabethOkerio** [comment]
@ogysha we'll appreciate a contribution on this.

**Comment by FH-Inway** [comment]
@AndreasHassing Do you mean the `NavigationProperty` tags under the `EntityType`?

**Comment by AndreasHassing** [comment]
> @AndreasHassing Do you mean the `NavigationProperty` tags under the `EntityType`?

That's right.
