### ISSUE TITLE
Next release ETA?

### ISSUE THREAD

**Issue by johnwc** [OData/ODataConnectedService#332]
There are bugs in the current released version of the VS extension that is causing issues for us, that are now fixed. Specifically, PR #311. When will the next release to VS marketplace be?

**Comment by habbes** [comment]
@johnwc Release planned within this week.

**Comment by johnwc** [comment]
@habbes How can we tell it to not include a `Generation date` at the top of every file? We are not really interested in that information being in the file, and when we have to update the code based on schema updates, it causes every file to show as being edited in source control. When in reality only one file was updated.

**Comment by batetech** [comment]
@johnwc  I implemented the option to exclude the generation date using `--disable-generation-date` on my branch here https://github.com/batetech/ODataConnectedService/tree/NoTimestampOption 

I haven't had time to finish fully testing it yet, but if you could help test it I can submit a pull request here for this.  

This branch also includes an option `--use-data-service-collection` which aligns with the "Enable Entity and Property Tracking" advanced option in the VS Extension.

**Comment by johnwc** [comment]
We only use the VS extension, so it'd have to be an option for us to test in that and not command line.

**Comment by batetech** [comment]
> We only use the VS extension, so it'd have to be an option for us to test in that and not command line.

I added it to the VS Extension UI there also, but it is a little trickier to test if you already have the oData Connected Service extension installed and don't have the VS extension development tools installed. I'll hopefully have some time in next few weeks to finish testing this.

**Comment by gathogojr** [comment]
Release completed
