### ISSUE TITLE
odata-cli ignore exclude-schema-types

### ISSUE THREAD

**Issue by wondertalik** [OData/ODataConnectedService#341]
### Describe the bug
odata-cli ignore exclude-schema-types options installed with dotnet tool.
so i cloned repo and run in Debug mode  Microsoft.Odata.Cli with arguments
```
generate  -est Nav.AbsenceRegistration --metadata-uri "C:\OData4Meta.xml" --outputdir HttpOData4Api.Infrastructure.Data/DataProviders/BusinessCentral/OData4 --namespace-prefix "HttpOData4Api.Infrastructure.Data.DataProviders.BusinessCentral.OData4" --multiple-files --upper-camel-case
```
![image](https://user-images.githubusercontent.com/1611064/231436275-67c8f7f7-b320-4b1e-bd56-5ac48efd5582.png)

![image](https://user-images.githubusercontent.com/1611064/231436348-32f50f64-7aa5-4290-918d-dbbbbf6352f5.png)

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/ODataConnectedService/pull/364. @wondertalik - Please test to verify
