### ISSUE TITLE
Wrong handling of default value of Edm.Date property

### ISSUE THREAD

**Issue by HeikoTheissen** [OData/ODataConnectedService#342]
### Describe the bug
A default value of a property of type `Edm.Date` is wrongly handled as an integer.

#### Version of the Project affected
ODataConnectedService 2022+ v1.0.1
Microsoft Visual Studio Professional 2022 (64-bit) v17.5.4
Microsoft.Odata.Client v7.15.0

#### To Reproduce
Import the following OData V4 metadata:
```
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="self" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityContainer Name="EntityContainer">
        <EntitySet Name="Dates" EntityType="self.Date" />
      </EntityContainer>
      <EntityType Name="Date">
        <Key>
          <PropertyRef Name="id" />
        </Key>
        <Property Name="id" Type="Edm.Guid" Nullable="false" />
        <Property Name="date" Type="Edm.Date" DefaultValue="9999-12-31" />
      </EntityType>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

#### Expected behavior
Generation of a working C# OData client.

#### Actual behavior
The following line of C# code is produced:
```
private global::System.Nullable<global::Microsoft.OData.Edm.Date> _Date1 = 9999-12-31;
```
in which the default value for the Edm.Date property seems to be an arithmetic expression evaluating to the integer 9956. This leads to the error
> Cannot implicitly convert type 'int' to 'Microsoft.OData.Edm.Date?'

#### Screenshots
n/a

#### Additional context
n/a

**Comment by habbes** [comment]
Seems like we're emitting the default value as-is without considering that it's a date. Thanks for reporting this,
