### ISSUE TITLE
Add ODataCLI option to not write Generation date into generated files

### ISSUE THREAD

**Issue by rpallares** [OData/ODataConnectedService#349]
### Is your feature request related to a problem? Please describe.  
We are using odata-cli in command line into our pipeline flows.  
The generated files always have a change on their headers with that line:  
// Generation date: 26/05/2023 15:39:04  

This produce lot of necessary noise to our developers.

#### Describe the solution you'd like
Have an option in odata-cli command line to not output generation date

#### Describe alternatives you've considered
Ignore the generated files from our VCS and only generated them on the fly.  
Unfortunately we are working in .Net 7 and odata-cli is still not available in .Net 7, making all our flows more complex by doing that (even if it would be better).  
That date is anyway redundant with our VCS history

#### Additional context
Here is a git diff view with the change:
![image](https://github.com/OData/ODataConnectedService/assets/11596864/3b904ab2-d4c5-4916-b011-a2c07205ec5a)

**Comment by FH-Inway** [comment]
Nice option, especially if multiple files are generated.
Thanks @gregwinterstein for the pr, works well for me.

**Comment by aboryczko** [comment]
@ElizabethOkerio any plans on rolling out a new version of the cli that would include this feature?

**Comment by ElizabethOkerio** [comment]
@aboryczko Yes we plan on doing a release.. Following up with some pending PRs to get them merged.
