### ISSUE TITLE
Support Arm64 Visual Studio

### ISSUE THREAD

**Issue by tfaller** [OData/ODataConnectedService#374]
### Is your feature request related to a problem? Please describe.
This extension currently does not support Arm64 Visual Studio.
I can't use it with my Visual Studio 2022 Arm64.

#### Describe the solution you'd like
Fully support Arm64 Visual Studio.
Please build for Arm64 architecture and publish it at the Visual Studio Marketplace.

**Comment by xuzhg** [comment]
'This extension currently does not support Arm64 Visual Studio.'  ==> What's the error message did you see?

It seems our manifest contains Amd64 at 
 'https://github.com/OData/ODataConnectedService/blob/master/src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest#L14-L20'

**Comment by tfaller** [comment]
I get the same excpetion as in #375.
The issue is, that the manifest only contains Amd64, but not Arm64 was well.

**Comment by GripService** [comment]
i think the work around is download source code and run it , it will open visual studio then open your project and you do not need to install odata if you will be checking connected service this should be there already
