### ISSUE TITLE
Generated Container Is in 'Default' Namespace

### ISSUE THREAD

**Issue by Alfetta159** [OData/ODataConnectedService#377]
I cannot see how to place the generated `Container` class into a namespace other than `Default`. This could be a problem if everyone using these generated objects can't differentiate between different instances of different types of this class. Bug, feature, or am I missing something? All other data objects are in a custom namespace, but the container is not.

* Container class:
```c#
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }
```

* Data object class:
```c#
namespace SunAuto.VastOdata.Services.VastOffice
{
    /// <summary>
    /// There are no comments for MasterSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MasterSingle")]
    public partial class MasterSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Master>
    {
        /// <summary>
        /// Initialize a new MasterSingle object.
        /// </summary>
        public MasterSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}
```

**Comment by aboryczko** [comment]
you probably have the Default Namespace used in your OData Model. if you change it in the metadata it will be reflected in the generated client, you can also override the namespace in the generator

**Comment by Alfetta159** [comment]
@aboryczko , What are you referring to when you say, "OData Model"? There are many models used by the EF database context that I am using, but they are just exposed in the OData controllers each representing a DBSet in the EF DB context. Where would I be designating this, "Default Namespace" in the OData API?

**Comment by aboryczko** [comment]
@Alfetta159 by "OData Model" I mean the EDM that you specify to ASP.NET probably in your Startup
```c#
ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
builder.Namespace = "Your.Namespace"
builder.ContainerName = "CustomService"
```
instead of Default.Container you would get Your.Namespace.CustomService when generating a client from this models metadata document
