### ISSUE TITLE
Generated files contain a timestamp that is more harmful than helpful

### ISSUE THREAD

**Issue by jphorv-bdo** [OData/ODataConnectedService#379]
### Is your feature request related to a problem? Please describe.
Yes - the problem is that the file(s) generated include a comment showing the `Generation date` as a date/time. This makes it difficult to see what files have _really_ changed when re-running/updating the connected service, because _all_ files get changed at least to have an updated `Generation date`.

#### Describe the solution you'd like
I would like it to either:

- a) not write the `Generation date` comment at all
- b) have an option to disable writing the `Generation date` comment

#### Describe alternatives you've considered
None.

#### Additional context
Here are the top few lines of a generated file that show the `Generation date` comment:

``` csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/14/2024 5:49:22 PM
namespace MyServiceNamespace.Entities
{
```

**Comment by gregwinterstein** [comment]
This issue resolved by this pull request:
#362 

Runtime Version changes also add to source control churn and that has not yet been addressed.

**Comment by jphorv-bdo** [comment]
That's great! How long until a new release is made?

**Comment by gregwinterstein** [comment]
@jphorv-bdo I'm sorry, I don't know when the next release will be made. That is a question for the owners/maintainers of this project.

**Comment by habbes** [comment]
Thanks @gregwinterstein @jphorv-bdo you're right in that we're long overdue for a release. We'll have the next release next week latest or by end of this week earliest.

**Comment by habbes** [comment]
As for removing the runtime version, that makes sense as well @jphorv-bdo, it could be the subject of a separate PR.

**Comment by habbes** [comment]
@gregwinterstein @jphorv-bdo We'll create a single flag that will disable both the runtime version and timestamp options from being emitted. This means we'll also rename the previously merged `no-timestamp` flag to something more generic.

cc @gathogojr
