### ISSUE TITLE
Passing ServiceName as command line argument

### ISSUE THREAD

**Issue by ellizio** [OData/ODataConnectedService#384]
### Is your feature request related to a problem? Please describe.
Metadata file from odata.cli tool is always named `OData ServiceCsdl.xml`.
If you generate two references, the assembly will contain two resources with the same name ending, which will throw an exception in `GeneratedEdmModel.CreateXmlReader()`

#### Describe the solution you'd like
Add optional --service-name (-sn) argument to the `generate` command to override the DefaultServiceName constant

#### Describe alternatives you've considered
I need to manually change resource name in Reference.cs and OData ServiceCsdl.xml filename

#### Additional context

**Comment by ellizio** [comment]
I'm ready to provide PR

**Comment by gathogojr** [comment]
Hi @ellizio. Thank you for reporting this issue. If you're able to contribute a pull request we'd be happy to review.

**Comment by ellizio** [comment]
@gathogojr I have opened pull request https://github.com/OData/ODataConnectedService/pull/389
