### ISSUE TITLE
Microsoft.OData.Cli 0.3.0 enable-tracking no longer working

### ISSUE THREAD

**Issue by emyklebost** [OData/ODataConnectedService#390]
There seems to be a regression when upgrading Microsoft.OData.Cli from 0.2.0 to 0.3.0.
Using an unmodified metadata.xml the new version no longer generate property tracking when the `--enable-tracking` flag is used.

### Assemblies affected

Microsoft.OData.Cli 0.3.0

### Reproduce steps

Generate client using odata-cli version 0.3.0 and the `--enable-tracking` flag.

### Expected result

Generated entities shall implement `INotifyPropertyChanged`.

### Actual result

Generated entities does **not** implement `INotifyPropertyChanged`.

**Comment by corranrogue9** [comment]
@gathogojr  believes there's already a fix for this pending release, but he will take a look at reproing before the release.

**Comment by gathogojr** [comment]
@emyklebost The workaround currently is to explicitly specify `true` or `false`, e.g., `--enable-tracking true` or `--enable-tracking false`.
You can find a comprehensive description of the problem and the solution in the description for [this](https://github.com/OData/ODataConnectedService/pull/392) pull request
