### ISSUE TITLE
Microsoft.OData.Cli 0.3.0 --multiple-files no longer working

### ISSUE THREAD

**Issue by rpallares** [OData/ODataConnectedService#391]
There seems to be a regression when upgrading Microsoft.OData.Cli from 0.2.0 to 0.3.0.
Using an unmodified metadata.xml the new version no longer generate multiple files when the --multiple-files flag is used.

#### Version of the Project affected
Microsoft.OData.Cli 0.3.0

#### To Reproduce
1. Generate client using odata-cli version 0.3.0 and the --multiple-files flag
2. Observe the client is generated in one unique file

#### Expected behavior
The client shall be generated with multiple files

#### Actual behavior
The client is generated into one unique file that contains all classes

#### Additional context
The root cause is probably similar to https://github.com/OData/ODataConnectedService/issues/390 where some command options look ignored.

**Comment by gathogojr** [comment]
Hi @rpallares. Thank you for bringing this issue to our attention.

The workaround currently is to explicitly specify `true` or `false`, e.g., `--multiple-files true` or `--multiple-files false`.
You can find a comprehensive description of the problem and the solution in the description for [this](https://github.com/OData/ODataConnectedService/pull/392) pull request

**Comment by rpallares** [comment]
Thx for the analysis, the PR and the workaround. 
I personally changed to use the configuration file that fit nice with my pipeline. But it's nice to see that fixed.
