### ISSUE TITLE
Releases aren't published to the Visual Studio Marketplace

### ISSUE THREAD

**Issue by jphorv-bdo** [OData/ODataConnectedService#394]
### Describe the bug
Changes and improvements are made in this repo, but for me it's all for nothing because the version on Visual Studio Marketplace never changes and my employer policy prevents the use of unsigned/unapproved extensions.

#### Version of the Project affected
ODataConnectedService 2022+ version 1.0.2
https://marketplace.visualstudio.com/items?itemName=marketplace.ODataConnectedService2022

#### To Reproduce
1. Watch this repo attentively as long-awaited improvements are made and even given version numbers.
2. Check Visual Studio Marketplace for those improvements to arrive.
3. GOTO 2
4. ....
5. Wonder what foul deed I committed in a past life to deserve this cruel torment. To see the work of many months, done, sitting here, yet untouchable. Supernatural punishment is the only plausible explanation.

#### Expected behavior
I expect that when releases are made, they are published and usable by the general public.

#### Actual behavior
Regular disappointment with no end in sight.

**Comment by gathogojr** [comment]
Hi @jphorv-bdo. Thank you for your patience. We had a few blockers that we have since dealt with. The latest VSIX is now available on VS marketplace.

**Comment by jphorv-bdo** [comment]
Thank _you_, I grabbed it and enjoyed it immediately.
