### ISSUE TITLE
Allow to set labels for created issues and PRs

### ISSUE THREAD

**Issue by unchase** [OData/ODataConnectedService#44]
Is it possible to give the opportunity to set Labels for own created issues and PRs?

What types of Labels are generally available?

**Comment by marabooy** [comment]
Seems like gihub doesn't support this as the member should have write access to the repo for it to work. https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests

**Comment by unchase** [comment]
Possible solutions:

* https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/issues/258#issuecomment-551516384
* [add more **ISSUE_TEMPLATE**](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates) with various labels

@habbes could you watch it?

**Comment by habbes** [comment]
It seems this has now been sorted @unchase ?

**Comment by unchase** [comment]
> It seems this has now been sorted

@habbes How?

**Comment by habbes** [comment]
@unchase I've seen that you have been able to add labels to issues.

**Comment by unchase** [comment]
> @unchase I've seen that you have been able to add labels to issues.

@habbes Unfortunately I can not

**Comment by unchase** [comment]
Can you resolve the issue?
This would greatly simplify the work with PRs and issues.
