### ISSUE TITLE
Issues with custom headers feature

### ISSUE THREAD

**Issue by habbes** [OData/ODataConnectedService#49]
### Describe the bug
The custom http feature (PR #27) was merged with some bugs and issues that were not caught by the reviewers:
- You cannot add custom http headers when updating the connected service
- An error occurs when the the "Add code templates" feature is enabled
- There should be some help text describing what the feature does, or provides an example of syntax (this is a suggestion, not a bug)
- It would be better if the custom headers feature was hidden by default and toggled if the user wants to see it (similar to how Advanced Settings are toggled) (this is a suggestion, not a bug)

### Version of the Project affected
Issues seem to have been introduced by [this commit](https://github.com/OData/ODataConnectedService/commit/288e7f9b61f8266c4ce5c1dfe421c06d350631d3)

#### 1. Adding custom headers when updating connected service

Create a project and generate client code using the OData Connected Service. Now right-click the connected service from the solution explorer and click "Update Connected Service". You'll notice that the custom headers text box is disabled, if the some headers were necessary for the extension to fetch the metadata from the service, then this means that it becomes effectively impossible for the client code to be updated.

**Proposed solution**: Enable the custom headers field when updating the connected service.

![image](https://user-images.githubusercontent.com/8460169/76973969-aa596f00-6941-11ea-9e42-42e8bb0ad4fe.png)

#### 2. Error when the "Add code templates" setting is enable

When adding an OData Connected Service to your project, if you enable the "Add code templates" option in Advanced settings, it adds the T4 `.tt` and `.ttinclude` template files to your project instead of the generated proxy classes. However, it appears that this feature no longer works correctly since the custom http headers feature was merged.

The following error is thrown when you try to create the service with the option to add code templates enabled.

![image](https://user-images.githubusercontent.com/8460169/76974428-3ec3d180-6942-11ea-96ed-94abf22de56a.png)

It appears that this error only occurs if you leave the custom headers empty. When you add some headers and enable the code templates option, then the error does not occur, and the templates are added as usual.

#### 3. Help text describing what the feature is about

Some people have requested that we add a brief description (or tooltip) explaining what the custom http feature is about (e.g. https://github.com/OData/ODataConnectedService/pull/27#issuecomment-599978324). I think the description should also mention what syntax is expected.

#### 4. Hide the feature by default behind a toggle

This is just a suggestion aimed at reducing noise/clutter on the first page from features that most users might not use. I suggesting adding a check box with the "Add custom headers" label. When the checkbox is checked, then the headers text box and description of the feature should appear.

**Comment by marabooy** [comment]
@habbes I think it may be time to close this now as the fixes are now included.

**Comment by KenitoInc** [comment]
Issues were resolved. Closing this now! cc @habbes @marabooy
