### ISSUE TITLE
Unable to cast object of type 'System.Net.FileWebRequest'

### ISSUE THREAD

**Issue by kornakar** [OData/ODataConnectedService#56]
### Describe the bug
On the first page of the wizard, when clicking Next or Finish button, I get a message box stating that:

> Unable to cast object of type 'System.Net.FileWebRequest' to type 'System.Net.HttpWebRequest'.

#### Version of the Project affected
ODataConnectedService v0.6.0
VisualStudio Version v15.9.16
Microsoft.Odata.Client v7.5.0.20627

#### To Reproduce
1. Select Update OData Connected service on the context menu
2. Click Next or Finish

#### Expected behavior
The OData client should be generated.

#### Actual behavior
Unable to cast object of type 'System.Net.FileWebRequest' to type 'System.Net.HttpWebRequest'.

#### Screenshots
![2020-03-23 10_58_40-Configure OData Connected Service](https://user-images.githubusercontent.com/1921540/77299987-029fc080-6cf6-11ea-9fdd-59e9754da26d.png)

#### Additional context
Versions 0.3.0 and 0.3.3 have worked fine.

Version **0.5.0** generated the client successfully, but the source code didn't compile because:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'System.Collections.Generic.IDictionary<string, object>' to 'System.Collections.Generic.Dictionary<string, object>'	MySolution.ODataClient	C:\Users\...\Connected Services\OData Service\Reference.cs	140793	Active
```

**Comment by unchase** [comment]
This bug is reproduced when loading local metadata files.
