### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by habbes** [OData/ODataConnectedService#59]
## Overall testing gaps:
- Verifying that options set by the user in the wizard are correctly propagated to the CodeGenerator instance
- Verifying that options set in the wizard are saved to the designer data (ConnectedService.json) as expected
- Verifying that settings are loaded from the designer data and used to populate the view when the connected service is being update
- Verify that settings that should be disabled during an update are disabled and settings that are mutually exclusive behave correctly (e.g. settings which should be disabled if T4 templates option is enabled)
- Verify that the T4 templates are generated correctly with the user-defined options stored in the Configuration class as expected
- Verify that settings that should only be available for v4 are treated as expected

### ODataConnectedServiceProvider
This is the entry point of the connected service. It doesn't do much besides `CreateConfiguratorAsync()` which simply creates an `ODataConnectedServiceWizard` instance
and returns it. I don't think it's very critical to test if `ODataConnectedServiceWizard` is thoroughly tested.

### ODataConnectedServiceWizard

This is the actual wizard. A new instance is created when creating or updating a connected service.
Handles the logic for populating the service config from the UI fields (user input) and populating
the UI with previously saved data when updating the connected service. The `GetFinishedServiceInstanceAsync`
is called by VS Connected Service engine and it returns the service instance that contains the config.

This class is lacking in critical tests:
- [x] user settings are loaded when the wizard is created
- [x] When the service is being updated, it should load saved config from `GetExtendedDesignerData()`
and use it to populate the view models accordingly. Test that the right fields are set to the view
models based on the saved config
- [x] Some fields should not be modified after code generation. When the connected service is updating,
ensure that these fields are disabled (e.g. T4 templates, Service Name, Service Endpoint, Generate multiple files, etc.)
- [x] Some fields should only be saved to config (and loaded from saved config) when connected to a V4 endpoint (e.g.
open generated fields in IDE, T4 templates, generate multiple files, etc.). I think this should apply to most
new settings that impact the generated code since we're not adding new features to generated code for v3 endpoints.
- [x] `CreateServiceConfiguration()` returns a `ServiceConfiguration` instance with values corresponding to fields
in the view models.
- [x] `GetFinishedServiceInstanceAsync()` saves user settings, creates a service instance based on the view models values
and service config, and returns that. The result of this method will be passed to the `ODataConnectedServiceHandler` so
testing this is critical in ensuring that values will be correctly propagated to the handler
- [ ] The `ObjectSelectionViewModel` is added to the wizard pages when leaving the endpoint page, if connecting to a v4 endpoint
- [x] When entering the object selection page, the edm model loaded and used to populate the view model with operation imports

### ConfigODataEndpointViewModel

Handles the endpoint config page of the wizard, also fetches the model from the provided endpoint.
`OnPageLeavingAsync()` is called when the page is leaving, and it handles a lot of logic that's not tested:

- [ ] Should add the provided endpoint to the user setting's most-recently used list when leaving the page
- [x] Should fetch metadata when from the provided endpoint when leaving the page and save it to a temporary file
- [x] Should detect and set the edmx version from the metadata
- [x] Should be able to fetch metadata if the endpoint is a local file
- [ ] Should pass provided custom headers to the web request when fetching metadata from a service
- [ ] Should be able to fetch metadata when behind web proxy

### SchemaTypesViewModel
- [x] `LoadSchemaTypes` creates a list of schema types that are all selected, ordered by name
- [x] Selecting a type also selects all its related types
- [x] when leaving the page, if there are unselected types which are required by some selected types, the required unselected types should be auto-selected and an appropriate message shown to the user
- [x] `ExcludeSchemaTypes` should deselect the specified types
- [x] select all functionality
- [x] deselect all functionality
- [x] `ExcludedSchemaTypeNames` should return a collection of the full names of the excluded types

### OperationImportsViewModel
This class has some tests, but there's new behaviour that was added with the schema types feature that's not covered by the unit tests
- [ ] when loading operation imports, if the operation has a parameter or return value that's of a type that was excluded, then the operation import should also be deselected
- [ ] when an operation import is selected, related schema types (parameter/return types) should also be selected

### ODataConnectedServiceHandler

This is called by the Connected Service engine when the user finishes configuring the wizard. It kicks off the code
generation process and saves the config settings to the designer data (`ConnectedService.json`). This can be considered
the bridge between the connected service UI logic and the code generation process.

It has two main methods `AddServiceInstanceAsync()` which is called when it's a new connected service, and `UpdatedServiceInstanceAsync()`,
which is called whene updating an existing connected service. Both methods initiate code generation process via a `CodeGenDescriptor`
and save the service config.

I added test cases for these methods when I first worked with this project. You may find the tests (`ODataConnectedServiceHandlerTests`) and associated helper classes (`TestconnectedServiceHandlerHelper` and `TestConnectedServiceHandlerContext`) useful as a reference if you have your tests need to mock out
classes from the VS or Connected Service SDKs. Some tests may still be missing:

- [x] Sensitive values like `ServiceConfig.CustomHttpHeaders` and proxy config/credentials should not be saved to the designer data

### V4CodeGenDescriptor
This class handles code generation for v4 endpoints. I added test cases to verify that it passes settings to
the `T4CodeGenerator` instance, and that saves the generated code at the right location, but it still lacks
many essential tests:
- [x] `AddNugetPackagesAsync()` should add the relevant OData client libraries to the project (`Microsoft.OData.{Client, Core, Edm}` and `System.Spatial`)
- [x] `AddGeneratedClientCodeAsync()` should add the t4 template files to the project if the corresponding option was enabled, otherwise it should generated c# files and add them to the project
- [x] `AddT4FileAsync()` should add the T4 template .tt and .ttinclude files to the reference folder (`<Project Root>\<Connected Services>\<Service Name>`)
- [x] Configuration values in the .tt file should be replaced with corresponding values from the Service Config. This should account
for service config value which may be `null`
- [x] `AddGeneratedCSharpCodeAsync()` should pass the values from the service config to the code generator instance. This should also account for `null`. This is partially tested but new config properties like `CustomHttpHeaders` are not tested. Should be upated to ensure
all config properties are tested.
- [x] The generated files should should saved at the right location (`<Project Root>\<Connected Services Root>\<Service Name>\<FileName>.cs`). I think there's a test case for this. But it does not handle the case where multiple files are generated.
- [ ] The metadata should be saved in Csdl.xml file in the connected service folder, and should configured as an embedded resource and its path should be used as the temp metadata path of the code generator
- [x] for VB projects, we should also test that the code generator is configured accordingly, and generated files are stored with the expected extension

### UserSettings
- [x] Saves settings when Save() is called
- [x] Loads previously saved settings when Load() is called, returns an instance of `UserSettings`
- [x] AddToTopOfMruList should add/move the item at the top of the list, without duplicating it if it already exists and without exceeding the maximum allowed entries (10 items)

### UserPersistenceHelper
Handles saving and loading of user settings to/from file. This class might be tested implicitly when testing the `UserSettings` class
- [ ] Saving settings
- [ ] Loading settings

### ProjectHelper
Helpers for working with the VS project. This may be tested implicitly when testing the `CodeGenDescriptor`s,
- [x] `GetProjectFromHiearchy` returns a `Project` from the given vs hiearchy
- [x] `GetFullPath` returns the full path of the project
- [x] `GetLanguageOption` determine whether the given project is a C# or a VB project

### EdmHelper
Helpers to parse and get data from an edm model. This is tested implicitly be the ODataConnectedServiceWizard tests. But it may be useful to have unit tests for it too
- [x]  `GetEdmFromFile` reads and returns an edm model from the given file
- [x] `GetOperationImports` returns operation imports from the model
- [x] `GetBoundOperations` returns bound operations from the model
- [x] `GetSchemaTypes` returns all schema types (entity, enum, complex, etc.) from the model
- [x] `GetTypeNameFromFullName` extract the type name without the namespace from a fully qualified name

### V3CodeGenDescriptor
- [x] `AddNugetPackageAsync` should install the V3 specific nuget packages
- [x] `AddGeneratedClientCodeAsync` should generate client code in the project language (C# or VB)

### Advanced settings
- [ ] most of the settings are hidden by default, click the "Advanced settings" link should make them visible

**Comment by unchase** [comment]
@habbes could you please review PR #38 before this, as with each change it is more and more difficult to resolve conflicts. Thanks.

**Comment by unchase** [comment]
@habbes test cases for **SchemaTypesViewModel** section was added in PR #117
