### ISSUE TITLE
Odata Connected Service not showing up

### ISSUE THREAD

**Issue by wurst0815** [OData/ODataConnectedService#60]
Hi,

I tried to follow the instructions from here http://odata.github.io/odata.net/#OData-Client-Code-Generation-Tool to add an OData Endpoint to my Visual Studio Solution.

In VS2015 Enterprise Update 3, Odata Connected Service is not offered.
![grafik](https://user-images.githubusercontent.com/13557494/33771905-145340be-dc33-11e7-95d3-04b730caa1bc.png)
 

In VS2017 Enterprise Version 15.4.5 I was able to install OData Connected Service Version 0.3.0
![grafik](https://user-images.githubusercontent.com/13557494/33770815-430f520c-dc2f-11e7-9082-5e8ea55e974a.png)

But when I try to add an OData Endpoint, all I'm offered is "Cloud Storage with Azure", no Odata.
![grafik](https://user-images.githubusercontent.com/13557494/33772071-a86fe450-dc33-11e7-8c71-51924e706020.png)

What am I doing wrong?

**Comment by habbes** [comment]
@wurst0815 OData Connected Service has been updated and now supports both C# and VB.NET in VS 2017 and 2019. Install the latest version from the [marketplace](https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService) and try it out.

Closing the issue. If you still face issues, feel free to re-open this issue or create a new one.
