### ISSUE TITLE
ClientCodeGenerator not working in VB.NET

### ISSUE THREAD

**Issue by wurst0815** [OData/ODataConnectedService#62]
When trying to create a proxy class following the documentation
https://blogs.msdn.microsoft.com/odatateam/2014/03/11/tutorial-sample-how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class/

in a VB.NET Solution, nothing happens. After right-clicking the T4 template -> Run Custom Tool nothing happens.
The same in C# works fine.
TargetLanguage was set to VB correctly
Both on VS2015

On VS2017 I get

![image](https://user-images.githubusercontent.com/13557494/42219267-a83c9a60-7ecb-11e8-8150-79ed240665ba.png)

for both, C# and VB

**Comment by paulodero** [comment]
@wurst0815 `OData Connected Service 0.7.0` now generates working `VB.NET` code.
