### ISSUE TITLE
Documentation links are broken for the client code generator

### ISSUE THREAD

**Issue by TWolverson** [OData/ODataConnectedService#63]
The "OData .Net Client" http://odata.github.io/odata.net/#04-01-basic-crud-operations link in the readme doesn't link to documentation on how to use the generated client. The linked section is nothing to do with the client code. I would expect to see some explanation and examples of how to use e.g. `public partial class [name of generated context] : global::Microsoft.OData.Client.DataServiceContext` that appears to be the entry point for the generated code.

In fact, I can't find anything anywhere, with a fair amount of googling, that tells you how to do anything at all with the generated code.

**Comment by KenitoInc** [comment]
Hey @TWolverson 
Does information in the link below solve your problem?
https://docs.microsoft.com/en-us/odata/client/basic-crud-operations

**Comment by KenitoInc** [comment]
@TWolverson 
We added the OData connected service docs  https://docs.microsoft.com/en-us/odata/connectedservice/getting-started
They contain the information that you need.
