### ISSUE TITLE
Save the wizard pages state

### ISSUE THREAD

**Issue by unchase** [OData/ODataConnectedService#69]
It would be nice to save the state of the wizard pages when a user navigates from page to page.

For example, the user selected the `OperationImports` to add, switched to another page, and then decided to change the selected `OperationImports`. 
With current behavior, he will have to choose everything anew.

Demostration:
![save_state](https://user-images.githubusercontent.com/29679226/77580424-0d707600-6eed-11ea-8de5-6bdc6c6833e7.gif)

**Comment by paulodero** [comment]
@unchase good idea. Could you share a contribution for this.

**Comment by unchase** [comment]
@paulodero perhaps, will be implemented automatically after merging PR #50
