### ISSUE TITLE
Can't access local .xml File nor hosted on a local webserver in Address Field

### ISSUE THREAD

**Issue by 0xtwi** [OData/ODataConnectedService#72]
For me it's impossible to ODataConnectedService. I need to use a local xml File.

Using ODataConnectedService Version 0.6.1:

I downloaded the xml File and entered the Path in the Address Field, now the Exception "Unable to cast object of type 'System.Net.FileWebRequest' to type 'System.Net.HttpWebRequest'.

My second attempt was to start a local Webserver (Mongoose) and while it's possible to access the File via WebBrowser on Localhost, ODataConnectedService will return an exception 404 after entering the Localhost Adress into the Address Field.

Can someone tell me how to use a Local File with ODataConnectedService?

**Comment by marabooy** [comment]
@0xtwi this has been fixed in the [0.7.0 release](https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService). Kindly update to the newest release to gain it's benefits.
