### ISSUE TITLE
Migrating code from OData V3 libraries

### ISSUE THREAD

**Issue by unchase** [OData/ODataConnectedService#79]
### Is your feature request related to a problem? Please describe.
At the moment, there is no support (development) for **OData V3** due to the fact that code generation occurs inside closed libraries. But a lot of users use exactly OData V3 (for example, to read some data from an on premise *Dynamics CRM*).
Perhaps, should migrate the code from the libraries in order to be able to solve generation errors.

#### Describe the solution you'd like
If you have the source code for these libraries, you can transfer them to the project.

#### Additional context
Are you going to support Odata V3 at all?

**Comment by unchase** [comment]
Could you comment on the possibility of solving this issue?

**Comment by habbes** [comment]
Hi @unchase , which features would you like to be supported on OData V3?
The fact that OData V3 code generation happens inside closed libraries is a limitation.

**Comment by unchase** [comment]
Hi, @habbes 
I wanted to clarify, could you extract the code out of closed OData V3 libraries to this Connected Service?

**Comment by habbes** [comment]
We cannot extract source code for OData V3 libraries. But the binaries can be found [here](https://github.com/OData/ODataConnectedService/tree/master/external/Binaries/V3)
