### ISSUE TITLE
Allow selecting which actions and functions to generate

### ISSUE THREAD

**Issue by habbes** [OData/ODataConnectedService#8]
Related to: https://github.com/OData/lab/issues/15

By default, OData Connected Service generates code for all types, functions and actions defined in the model, many of which may end up unused and polluting the user's application. We should allow the user to select a subset of functions/actions imports to be generated.

**Comment by unchase** [comment]
It would be nice to add the ability to select/exclude operation imports in the UI (in the new Connected Service Wizard page).
Can you implement this in PR #45?

**Comment by habbes** [comment]
@unchase yes definitely, that's the plan. The PR is still a draft precisely because I have not added that part yet. Thanks.

**Comment by unchase** [comment]
In addition to the name of the `OperationImport`, it is desirable to display its signature, since `OperationImports` with the same name can be overloaded.

**Comment by habbes** [comment]
@unchase for this version we're going for a simple approach. When you exclude a name from the list, then all operations with that name regardless of signature (i.e. all overloads) are excluded from the generated code. Since all overloads are excluded, then there's no point in displaying the signature since it doesn't affect anything in this case.

Maybe in a future version we could make it possible to exclude specific overloads of an operation.
