### ISSUE TITLE
Generator should skip or warn about existing types, not re-generate them

### ISSUE THREAD

**Issue by weitzhandler** [OData/ODataConnectedService#81]
### Describe the bug
The generator arbitrarily generates all types.
Some times, there are types (enum types for instance), that already exist in the client project and I don't want them generated.

The generator should detect all existing types, and warn about them, or ask the user whether these classes should be skipped or generated anyway.

#### Version of the Project affected
ODataConnectedService v0.7.1
VisualStudio Version v16.5.1
Microsoft.Odata.Client v7.6.4

#### To Reproduce
- Create a client-server project.
Have one of the OData types implement an interface defined in a shared file, exposing an enum property, which is also declared in the shared class.
- Generate the client proxies
- The enum should not be generated, it already exists in the shared file, to be exposed from the interface.

#### Screenshots

![image](https://user-images.githubusercontent.com/2716316/77902524-fed9e400-7289-11ea-83ef-5ab2c8b6c062.png)

**Comment by habbes** [comment]
@weitzhandler thanks for reporting this issue. We have PR #81 for allowing you to exclude types you don't want from the code generator.

**Comment by weitzhandler** [comment]
@habbes 

That wouldn't be a proper solution as it would still cause ambiguities and messy code.

Related: https://github.com/OData/odata.net/issues/1746

**Comment by weitzhandler** [comment]
I'm close the issue for now. Would be nice to have but with #71 on board it's bearable.
Should I encounter any blockers and I'll reopen.
Thanks for your time.
