### ISSUE TITLE
Feature: Add intermediate partial entity in-between BaseEntityType, or convert it to interface

### ISSUE THREAD

**Issue by weitzhandler** [OData/ODataConnectedService#88]
Hi,

It's very limiting that `BaseEntityType` is a class in a different assembly and can't really be expanded. This is very limiting for many scenarios, like validation and more.

Best solution would be introduce an `IBaseEntityType` interface that the generator implements explicitly instead of a concrete class, to enable inheriting from other types.

Otherwise, at least have an intermediate app-level base-class like `AppBaseEntityType` that is exposed as a partial class and allows for expansion.

Suggested here: https://github.com/OData/odata.net/issues/1735

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/odata.net/issues/1735
