### ISSUE TITLE
Add support for generic types

### ISSUE THREAD

**Issue by weitzhandler** [OData/ODataConnectedService#92]
Hi,

In my model I have a base entity of a generic type:

```c#
public abstract class DynamicDataValueBase<T> : DynamicDataValueBase { }
```

It gets generated to the client as:

```c#
public abstract partial class DynamicFieldValueBase_1OfT : DynamicFieldValueBase { }
```

**Comment by gathogojr** [comment]
@weitzhandler Kindly clarify, is this a feature request or you're reporting buggy behaviour?

**Comment by weitzhandler** [comment]
I see now the metadata, and looks like this is lack of the support in the EDMX.
So this issue belongs [here](https://github.com/OData/WebApi/issues/2117).
