### ISSUE TITLE
Name of last connected service is used when service name is left as default

### ISSUE THREAD

**Issue by habbes** [OData/ODataConnectedService#94]
### Describe the bug
When you create a connected service without modifying the service name, i.e. leaving the default "OData Service", the generated service is saved under the name of a previously generated connected service.

#### Version of the Project affected
ODataConnectedService on master branch (as of commit [46f7866](https://github.com/OData/ODataConnectedService/commit/46f78667e31cc8629774d4cd91aeaf7f8a2d7b7b))

#### To Reproduce
1. Create connected service, give it a service name, e.g. "ServiceA" and complete the code generation process
2.  Create another connected service, leave the default service name "OData Service" unchanged. Complete the code generation process.

#### Expected behavior
The code and files for the second connected service should be saved under "OData Service" subfolder with "OData Service" saved a the service name

#### Actual behavior
The generated code is saved under "ServiceA" and overwrites the code and files in the "ServiceA" subfolder. Furthermore the "ServiceName" in the generated ConnectedService.json file is saved as "ServiceA".

#### Additional context
- If you modify the service name field before code generation, the bug does not occur
- If you load a config file including the service name, the bug does not occur
- In the example provided in the repro-steps, if you were to create another service in between the two that loads the service name and other settings from a config file, the third service with a default service name would still be saved under "ServiceA", it seems that it picks the service name of the last saved connected service that did not load settings from a config file. Maybe the service name is saved in user settings when editing the field manually, but not saved in user settings when loading from a config file
- The bug did not occur in v0.7.1 that's on Marketplace, it seems to be a regression introduced by PR #50

**Comment by unchase** [comment]
@ElizabethOkerio @habbes fixed in PR #78
